/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const semantic = {
  background: {
    canvas: '#131414',
    danger: '#221919',
    dialog: '#030303',
    floating: '#030303',
    info: '#191d1f',
    interactive: {
      accent: {
        emphasis: {
          default: '#8cd2da',
          hover: '#ace3e9',
          pressed: '#c7f1f6',
        },
        muted: {
          default: '#191d1d',
          hover: '#3c6266',
          pressed: '#3e7378',
        },
        selected: {
          default: '#41878e',
          hover: '#439199',
          pressed: '#6ec0c9',
        },
      },
      danger: {
        emphasis: {
          default: '#ffa4a2',
          hover: '#ffc4c1',
          pressed: '#ffdddb',
        },
        muted: {
          default: '#221919',
          hover: '#923a3c',
          pressed: '#b03940',
        },
      },
      disabled: '#1b1c1d',
      neutral: {
        emphasis: {
          default: '#b4c7d7',
          hover: '#cadae7',
          pressed: '#deeaf4',
        },
        muted: {
          default: '#131414',
          hover: '#1b1c1d',
          pressed: '#525c65',
        },
        selected: {
          default: '#191d1d',
          hover: '#3c6266',
          pressed: '#3e7378',
        },
      },
      readOnly: '#1b1c1d',
      warning: {
        emphasis: {
          default: '#ffaf6b',
          hover: '#ffcba2',
          pressed: '#ffdebe',
        },
        muted: {
          default: '#201b17',
          hover: '#7e4e25',
          pressed: '#97571b',
        },
      },
    },
    inverted: '#d6e3ee',
    success: '#191d19',
    surface: '#030303',
    warning: '#201b17',
  },
  border: {
    accent: {
      medium: '#439199',
      strong: '#8cd2da',
      subtle: '#3e7378',
    },
    danger: {
      subtle: '#b03940',
    },
    info: {
      subtle: '#316f98',
    },
    interactive: {
      accent: {
        emphasis: {
          default: '#8cd2da',
          hover: '#ace3e9',
          pressed: '#c7f1f6',
        },
        muted: {
          default: '#3e7378',
          hover: '#41878e',
          pressed: '#439199',
        },
      },
      danger: {
        emphasis: {
          default: '#ffa4a2',
          hover: '#ffc4c1',
          pressed: '#ffdddb',
        },
        muted: {
          default: '#b03940',
          hover: '#d43745',
          pressed: '#e53748',
        },
      },
      disabled: '#1b1c1d',
      focus: '#2d8bc5',
      neutral: {
        emphasis: {
          default: '#b4c7d7',
          hover: '#cadae7',
          pressed: '#deeaf4',
        },
        muted: {
          default: '#5d6b76',
          hover: '#738696',
          pressed: '#9fb4c6',
        },
      },
      selectedIndicator: '#f1ffff',
      warning: {
        emphasis: {
          default: '#ffaf6b',
          hover: '#ffcba2',
          pressed: '#ffdebe',
        },
        muted: {
          default: '#97571b',
          hover: '#b46201',
          pressed: '#c26900',
        },
      },
    },
    neutral: {
      medium: '#5d6b76',
      strong: '#525c65',
      subtle: '#1b1c1d',
    },
    success: {
      subtle: '#3e793c',
    },
    warning: {
      subtle: '#97571b',
    },
  },
  cornerRadius: {
    none: 0,
    pill: 9999,
    rounded: 4,
    roundedOuter: 6,
  },
  dataVisualization: {
    cat: {
      '1': {
        '1': '#00282c',
        '2': '#00383c',
        '3': '#03484c',
        '4': '#5d8386',
        '5': '#adc3c4',
      },
      '2': {
        '1': '#544100',
        '2': '#a28200',
        '3': '#f4cb00',
        '4': '#f7db79',
        '5': '#f9eab5',
      },
      '3': {
        '1': '#003f6e',
        '2': '#0078b7',
        '3': '#4bb6fc',
        '4': '#8aceff',
        '5': '#e0c9ee',
      },
      '4': {
        '1': '#5e053e',
        '2': '#92376a',
        '3': '#c86499',
        '4': '#df96ba',
        '5': '#f4c8dc',
      },
      '5': {
        '1': '#153900',
        '2': '#315f00',
        '3': '#548723',
        '4': '#8ab06f',
        '5': '#c2d9b3',
      },
      '6': {
        '1': '#410a55',
        '2': '#622c79',
        '3': '#854b9e',
        '4': '#af86c2',
        '5': '#d9c1e5',
      },
      '7': {
        '1': '#590009',
        '2': '#7e1823',
        '3': '#a3383e',
        '4': '#ca7b7a',
        '5': '#edbcba',
      },
      '8': {
        '1': '#00432b',
        '2': '#007853',
        '3': '#00ad81',
        '4': '#75c9a8',
        '5': '#b7e5d1',
      },
      '9': {
        '1': '#052a70',
        '2': '#2a53a0',
        '3': '#507ed3',
        '4': '#87a9e7',
        '5': '#bfd4f9',
      },
      '10': {
        '1': '#671f00',
        '2': '#aa5215',
        '3': '#ed8b52',
        '4': '#f7b18a',
        '5': '#ffd5bf',
      },
    },
    div: {
      '1': '#539cec',
      '2': '#4579b2',
      '3': '#38577b',
      '4': '#2a3848',
      '5': '#1b1b1b',
      '6': '#443224',
      '7': '#724b2c',
      '8': '#a36530',
      '9': '#d78031',
    },
    seq: {
      '1': '#243032',
      '2': '#2a4f54',
      '3': '#14727b',
      '4': '#0096a4',
      '5': '#00b9c9',
      '6': '#5dd8e5',
      '7': '#acf3fb',
    },
  },
  fontFamily: {
    header: 'Equinor',
    ui: 'Inter',
  },
  fontWeight: {
    bolder: 500,
    lighter: 300,
    normal: 400,
  },
  icon: {
    accent: '#bcebf1',
    danger: '#ffc4c1',
    info: '#b0deff',
    interactive: {
      accent: {
        default: '#c7f1f6',
        hover: '#bcebf1',
        pressed: '#f1ffff',
      },
      danger: {
        default: '#ffc4c1',
        hover: '#ffdddb',
        pressed: '#ffd1ce',
      },
      disabled: '#6b7d8b',
      link: {
        default: '#5abbfb',
        hover: '#82cdff',
        pressed: '#b0deff',
      },
      warning: {
        default: '#ffcba2',
        hover: '#ffdebe',
        pressed: '#ffd7b3',
      },
    },
    inverted: '#131414',
    onEmphasis: '#030303',
    primary: '#d6e3ee',
    secondary: '#9fb4c6',
    success: '#aceba8',
    tertiary: '#738696',
    warning: '#ffcba2',
  },
  overlay: {
    scrim: '#1d1d1d1a',
  },
  spacing: {
    twoXl: 28,
    twoXs: 6,
    threeXl: 32,
    threeXs: 4,
    fourXs: 2,
    lg: 20,
    md: 16,
    none: 0,
    sm: 12,
    xl: 24,
    xs: 8,
  },
  text: {
    accent: '#bcebf1',
    danger: '#ffc4c1',
    info: '#b0deff',
    interactive: {
      accent: {
        default: '#ace3e9',
        hover: '#c7f1f6',
        pressed: '#bcebf1',
      },
      danger: {
        default: '#ffc4c1',
        hover: '#ffdddb',
        pressed: '#ffd1ce',
      },
      disabled: '#6b7d8b',
      link: {
        default: '#5abbfb',
        hover: '#82cdff',
        pressed: '#b0deff',
      },
      warning: {
        default: '#ffcba2',
        hover: '#ffdebe',
        pressed: '#ffd7b3',
      },
    },
    inverted: '#131414',
    onEmphasis: '#030303',
    primary: '#d6e3ee',
    secondary: '#9fb4c6',
    success: '#aceba8',
    tertiary: '#738696',
    warning: '#ffcba2',
  },
  typography: {
    header: {
      twoXl: {
        fontSize: 24,
        lineHeight: 28,
      },
      threeXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 32,
        lineHeight: 32,
      },
      lg: {
        fontSize: 18,
        lineHeight: 24,
      },
      md: {
        fontSize: 16,
        lineHeight: 20,
      },
      sm: {
        fontSize: 14,
        lineHeight: 16,
      },
      xl: {
        fontSize: 21,
        lineHeight: 24,
      },
      xs: {
        fontSize: 12,
        lineHeight: 16,
      },
    },
    ui: {
      twoXl: {
        fontSize: 21,
        lineHeight: 28,
      },
      threeXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 28,
        lineHeight: 32,
      },
      fiveXl: {
        fontSize: 32,
        lineHeight: 36,
      },
      lg: {
        fontSize: 16,
        lineHeight: 24,
      },
      md: {
        fontSize: 14,
        lineHeight: 20,
      },
      sm: {
        fontSize: 12,
        lineHeight: 16,
      },
      xl: {
        fontSize: 18,
        lineHeight: 24,
      },
      xs: {
        fontSize: 10,
        lineHeight: 16,
      },
    },
  },
} as const

export type Semantic = typeof semantic
