/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const semantic = {
  background: {
    container: {
      canvas: {
        default: '#131414',
      },
      card: {
        default: '#030303',
      },
      popover: {
        default: '#030303',
        inverted: '#d6e3ee',
      },
      sheet: {
        dialog: {
          default: '#030303',
        },
      },
    },
    surface: {
      accent: {
        default: {
          default: '#2c3839',
          hover: '#c7f1f6',
          pressed: '#030303',
        },
        selected: {
          default: '#41878e',
          hover: '#3c6266',
          pressed: '#439199',
        },
        subtle: {
          default: '#191d1d',
          hover: '#3e7378',
          pressed: '#3c6266',
        },
      },
      default: {
        active: '#1b1c1d',
        default: '#131414',
        disabled: '#131414',
        hover: '#1b1c1d',
        muted: '#131414',
        pressed: '#525c65',
        readOnly: '#131414',
        selected: {
          default: '#191d1d',
          hover: '#3c6266',
          pressed: '#3e7378',
        },
      },
    },
  },
  border: {
    default: '#5d6b76',
    disabled: '#738696',
    emphasized: '#525c65',
    focus: '#2d8bc5',
    hover: '#738696',
    selected: '#f1ffff',
    subtle: '#1b1c1d',
  },
  cornerRadius: {
    none: 0,
    pill: 9999,
    rounded: 4,
    roundedOuter: 6,
  },
  fontFamily: {
    heading: 'Equinor',
    ui: 'Inter',
  },
  fontWeight: {
    bolder: 500,
    lighter: 300,
    normal: 400,
  },
  icon: {
    accent: '#f1ffff',
    accentHover: '#2c3839',
    accentPressed: '#030303',
    colorOnDark: '#333639',
    colorOnLight: '#d6e3ee',
    disabled: '#6b7d8b',
    muted: '#738696',
    onAccent: '#333639',
    primary: '#cadae7',
    secondary: '#9fb4c6',
  },
  overlay: {
    scrim: '#1d1d1d1a',
  },
  spacing: {
    twoXl: 28,
    twoXs: 6,
    threeXl: 32,
    threeXs: 4,
    fourXs: 2,
    lg: 20,
    md: 16,
    none: 0,
    sm: 12,
    xl: 24,
    xs: 8,
  },
  status: {
    warning: {
      default: '#161311',
      emphased: {
        default: '#f99539',
        hover: '#ffdebe',
        selected: '#ffd7b3',
      },
      hover: '#7e4e25',
      selected: '#b46201',
    },
  },
  text: {
    accent: '#5abbfb',
    colorOnDark: '#333639',
    colorOnLight: '#d6e3ee',
    disabled: '#738696',
    muted: '#738696',
    onAccent: '#333639',
    pressed: '#b0deff',
    primary: '#d6e3ee',
    secondary: '#9fb4c6',
    status: {
      onDark: '#040303',
      onLight: '#ffdebe',
    },
  },
  typography: {
    header: {
      twoXl: {
        fontSize: 24,
        lineHeight: 28,
      },
      threeXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 32,
        lineHeight: 32,
      },
      lg: {
        fontSize: 18,
        lineHeight: 24,
      },
      md: {
        fontSize: 16,
        lineHeight: 20,
      },
      sm: {
        fontSize: 14,
        lineHeight: 16,
      },
      xl: {
        fontSize: 21,
        lineHeight: 24,
      },
      xs: {
        fontSize: 12,
        lineHeight: 16,
      },
    },
    ui: {
      twoXl: {
        fontSize: 21,
        lineHeight: 28,
      },
      threeXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 28,
        lineHeight: 32,
      },
      fiveXl: {
        fontSize: 32,
        lineHeight: 36,
      },
      lg: {
        fontSize: 16,
        lineHeight: 24,
      },
      md: {
        fontSize: 14,
        lineHeight: 20,
      },
      sm: {
        fontSize: 12,
        lineHeight: 16,
      },
      xl: {
        fontSize: 18,
        lineHeight: 24,
      },
      xs: {
        fontSize: 10,
        lineHeight: 16,
      },
    },
  },
} as const

export type Semantic = typeof semantic
