/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const semantic = {
  background: {
    container: {
      canvas: {
        default: '#f8f8f8',
      },
      card: {
        default: '#ffffff',
      },
      popover: {
        default: '#ffffff',
        inverted: '#404040',
      },
      sheet: {
        dialog: {
          default: '#ffffff',
        },
      },
    },
    surface: {
      accent: {
        default: {
          default: '#cae4e7',
          hover: '#20565c',
          pressed: '#ffffff',
        },
        selected: {
          default: '#a2cdd2',
          hover: '#87c0c6',
          pressed: '#6cb2b9',
        },
        subtle: {
          default: '#ddeff1',
          hover: '#bbdbdf',
          pressed: '#87c0c6',
        },
      },
      default: {
        active: '#ebebeb',
        default: '#f8f8f8',
        disabled: '#f8f8f8',
        hover: '#ebebeb',
        muted: '#f8f8f8',
        pressed: '#e1e1e1',
        readOnly: '#f8f8f8',
        selected: {
          default: '#ddeff1',
          hover: '#cfe7e9',
          pressed: '#bbdbdf',
        },
      },
    },
  },
  border: {
    default: '#d4d4d4',
    disabled: '#a4a4a4',
    emphasized: '#b4b4b4',
    focus: '#5cade5',
    hover: '#a4a4a4',
    selected: '#1e383a',
    subtle: '#ebebeb',
  },
  cornerRadius: {
    none: 0,
    pill: 9999,
    rounded: 4,
    roundedOuter: 6,
  },
  fontFamily: {
    heading: 'Equinor',
    ui: 'Inter',
  },
  fontWeight: {
    bolder: 500,
    lighter: 300,
    normal: 400,
  },
  icon: {
    accent: '#1e383a',
    accentHover: '#cae4e7',
    accentPressed: '#ffffff',
    colorOnDark: '#dedede',
    colorOnLight: '#404040',
    disabled: '#c4c4c4',
    muted: '#a4a4a4',
    onAccent: '#dedede',
    primary: '#5b5b5b',
    secondary: '#868686',
  },
  overlay: {
    scrim: '#1d1d1d1a',
  },
  spacing: {
    twoXl: 28,
    twoXs: 6,
    threeXl: 32,
    threeXs: 4,
    fourXs: 2,
    lg: 20,
    md: 16,
    none: 0,
    sm: 12,
    xl: 24,
    xs: 8,
  },
  status: {
    warning: {
      default: '#fff6f0',
      emphased: {
        default: '#c86a00',
        hover: '#753c00',
        selected: '#603204',
      },
      hover: '#fbdac1',
      selected: '#f0b689',
    },
  },
  text: {
    accent: '#1d8fcf',
    colorOnDark: '#dedede',
    colorOnLight: '#404040',
    disabled: '#a4a4a4',
    muted: '#a4a4a4',
    onAccent: '#dedede',
    pressed: '#006192',
    primary: '#404040',
    secondary: '#868686',
    status: {
      onDark: '#ffffff',
      onLight: '#753c00',
    },
  },
  typography: {
    header: {
      twoXl: {
        fontSize: 24,
        lineHeight: 28,
      },
      threeXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 32,
        lineHeight: 32,
      },
      lg: {
        fontSize: 18,
        lineHeight: 24,
      },
      md: {
        fontSize: 16,
        lineHeight: 20,
      },
      sm: {
        fontSize: 14,
        lineHeight: 16,
      },
      xl: {
        fontSize: 21,
        lineHeight: 24,
      },
      xs: {
        fontSize: 12,
        lineHeight: 16,
      },
    },
    ui: {
      twoXl: {
        fontSize: 21,
        lineHeight: 28,
      },
      threeXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 28,
        lineHeight: 32,
      },
      fiveXl: {
        fontSize: 32,
        lineHeight: 36,
      },
      lg: {
        fontSize: 16,
        lineHeight: 24,
      },
      md: {
        fontSize: 14,
        lineHeight: 20,
      },
      sm: {
        fontSize: 12,
        lineHeight: 16,
      },
      xl: {
        fontSize: 18,
        lineHeight: 24,
      },
      xs: {
        fontSize: 10,
        lineHeight: 16,
      },
    },
  },
} as const

export type Semantic = typeof semantic
