extends:
  - airbnb
  - prettier
plugins:
  - prettier
env:
  browser: true
  node: true
globals:
  test: true
  expect: true
rules:
  prettier/prettier:
    - error
  no-unused-vars:
    - error
    - varsIgnorePattern: ^React$
  import/prefer-default-export:
    - off
  no-underscore-dangle:
    - off
  no-use-before-define:
    - off
  # Problems using node aliases, mjs files and local npm packages so disabling import-rules for now
  import/no-unresolved:
    - off
