#image:
#  file: .gitpod.Dockerfile

tasks:
  - name: Install pnpm
    init: |
      npm i -g pnpm
      echo "Pnpm installed"
      gp sync-done pnpm
  - name: Install dependencies
    init: |
      gp sync-await pnpm
      pnpm Install
      pnpm recursive install --filter ./packages
      echo "Dependencies installed"
      gp sync-done install
ports:
  - port: 9000
    onOpen: open-preview

gitConfig:
  alias.co: checkout
  alias.br: branch
  alias.ci: commit
  alias.st: status
  pull.rebase: merges

vscode:
  extensions:
    - vtrois.gitmoji-vscode
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - pflannery.vscode-versionlens
