image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    before: |
      pnpm install
      pnpm recursive install --filter "./packages/**"
    init: |
      pnpm build:utils
      pnpm build:icons
      pnpm build:tokens
      gp sync-done install
    command: pnpm storybook:core-react
ports:
  - port: 9000
    onOpen: open-preview

gitConfig:
  alias.co: checkout
  alias.br: branch
  alias.ci: commit
  alias.st: status
  pull.rebase: merges

vscode:
  extensions:
    - vtrois.gitmoji-vscode
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - eamodio.gitlens
    - dbaeumer.vscode-eslint
    - pflannery.vscode-versionlens
