name: eds
engines:
  pnpm: '>=5.13.5'
scripts:
  lint: eslint
  'lint:all': pnpm run lint .
  'lint:storybook': pnpm run lint ./apps/storybook/stories
  'lint:eds-core-react': pnpm run lint ./libraries/eds-core-react/src
  init: pnpm multi install --force && pnpm run build
  eds-core-react: pnpm --filter @equinor/eds-core-react run dev
  'test:eds-core-react': pnpm --filter @equinor/eds-core-react run test
  'build:eds-core-react': pnpm --filter @equinor/eds-core-react run build
  'build:eds-tokens': pnpm --filter @equinor/eds-tokens run build
  'build:eds-icons': pnpm --filter @equinor/eds-icons run build
  'bump:eds-core-react': >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm version
    prerelease
  'publish:eds-core-react': >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm publish --tag
    alpha --access public
  storybook: pnpm --filter @equinor/eds-storybook run dev
  storefront: pnpm --filter @equinor/eds-storefront run dev
  'build:storefront': pnpm --filter @equinor/eds-storefront run build
  figma-broker: pnpm --filter @equinor/eds-figma-broker run dev
  'test:watch:eds-core-react': 'pnpm --filter @equinor/eds-core-react run test:watch'
  dockerize-storybook: docker build -t eds/storybook -f apps/storybook/Dockerfile.dev .
  storybook-docker-run: 'docker run -p 8080:80 eds/storybook'
  storybook-docker-inspect: docker run -it eds/storybook /bin/sh
  dockerize-storefront: >-
    docker build --build-arg GATSBY_STAGE=prod -t eds/storefront -f
    apps/storefront/Dockerfile .
  storefront-docker-run: 'docker run -p 8080:80 eds/storefront'
  storefront-docker-inspect: docker run -it eds/storefront /bin/sh
devDependencies:
  '@typescript-eslint/eslint-plugin': ^3.10.1
  '@typescript-eslint/parser': ^3.10.1
  babel-eslint: ^10.1.0
  eslint: ^7.14.0
  eslint-config-prettier: ^6.15.0
  eslint-plugin-import: ^2.22.1
  eslint-plugin-jsx-a11y: ^6.4.1
  eslint-plugin-prettier: ^3.1.4
  eslint-plugin-react: ^7.21.5
  eslint-plugin-testing-library: ^1.5.0
  prettier: ^2.2.1
  typescript: ^4.1.2
