name: eds
engines: { pnpm: '>=5.13.5' }
scripts:
  lint: eslint
  lint:all: pnpm run lint .
  lint:core-react: pnpm run lint ./libraries/core-react
  init: pnpm multi install --force && pnpm run build
  core-react: pnpm --filter @equinor/eds-core-react run dev
  test:core-react: pnpm --filter @equinor/eds-core-react run test
  build: pnpm run build:icons && pnpm run build:tokens && pnpm run build:core-react
  build:core-react: pnpm --filter @equinor/eds-core-react run build
  build:tokens: pnpm --filter @equinor/eds-tokens run build
  build:icons: pnpm --filter @equinor/eds-icons run build
  storybook: pnpm --filter ./libraries/core-react run storybook
  build:storybook: pnpm --filter ./libraries/core-react run build:storybook
  figma-broker: pnpm --filter @equinor/eds-figma-broker run dev
  test:watch:core-react: pnpm --filter @equinor/eds-core-react run test:watch
  test:update-snapshots:core-react: pnpm --filter @equinor/eds-core-react run test:update-snapshots
devDependencies:
  '@babel/core': ^7.13.15
  '@babel/eslint-parser': ^7.13.14
  '@typescript-eslint/eslint-plugin': ^4.21.0
  '@typescript-eslint/parser': ^4.21.0
  eslint: ^7.32.0
  eslint-config-prettier: ^8.3.0
  eslint-import-resolver-typescript: ^2.5.0
  eslint-plugin-import: ^2.25.2
  eslint-plugin-jsx-a11y: ^6.4.1
  eslint-plugin-prettier: ^3.4.1
  eslint-plugin-react: ^7.26.1
  eslint-plugin-react-hooks: ^4.2.0
  eslint-plugin-testing-library: ^4.12.4
  prettier: ^2.2.1
  typescript: ^4.2.4
