name: eds
scripts:
  build: pnpm --filter @equinor/eds-core-react run build
  bump:core-react: >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm version
    prerelease
  publish:core-react: >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm publish --tag
    alpha --access public
  build-storybook: >-
    pnpm --filter @equinor/eds-core-react install &&
    pnpm --filter @equinor/eds-core-react run build &&
    pnpm --filter @equinor/eds-storybook-react install &&
    pnpm --filter @equinor/eds-storybook-react run build
  dockerize-storybook: docker build -t eds/storybook-react -f apps/storybook-react/Dockerfile.dev .
  storybook-docker-run: docker run -p 8080:80 eds/storybook-react
  storybook-docker-inspect: docker run -it eds/storybook-react /bin/sh
devDependencies:
  eslint: ^6.0.1
  eslint-config-airbnb: ^17.1.1
  eslint-config-prettier: ^6.0.0
  eslint-plugin-prettier: ^3.1.0
  prettier: ^1.18.2
