name: eds
engines:
  pnpm: '>=4'
scripts:
  lint: eslint
  'lint:all': pnpm run lint .
  'lint:storybook': pnpm run lint ./apps/storybook-react/stories
  'lint:core-react': pnpm run lint ./libraries/core-react/src
  init: pnpm multi install --force && pnpm run build
  core-react: pnpm --filter @equinor/eds-core-react run dev
  'test:core-react': pnpm --filter @equinor/eds-core-react run test
  'build:core-react': pnpm --filter @equinor/eds-core-react run build
  'bump:core-react': >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm version
    prerelease
  'publish:core-react': >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm publish --tag
    alpha --access public
  storybook: pnpm --filter @equinor/eds-storybook-react run dev
  'build:storybook': >-
    pnpm --filter @equinor/eds-core-react install && pnpm --filter
    @equinor/eds-core-react run build && pnpm --filter
    @equinor/eds-storybook-react install && pnpm --filter
    @equinor/eds-storybook-react run build
  storefront: pnpm --filter @equinor/eds-storefront run dev
  'build:storefront': pnpm --filter @equinor/eds-storefront run build
  figma-broker: pnpm --filter @equinor/eds-figma-broker run dev
  test:watch:core-react: pnpm --filter @equinor/eds-core-react run test:watch
  dockerize-storybook: docker build -t eds/storybook-react -f apps/storybook-react/Dockerfile.dev .
  storybook-docker-run: 'docker run -p 8080:80 eds/storybook-react'
  storybook-docker-inspect: docker run -it eds/storybook-react /bin/sh
  dockerize-storefront: >-
    docker build --build-arg GATSBY_STAGE=prod -t eds/storefront -f
    apps/storefront/Dockerfile .
  storefront-docker-run: 'docker run -p 8080:80 eds/storefront'
  storefront-docker-inspect: docker run -it eds/storefront /bin/sh
devDependencies:
  '@typescript-eslint/eslint-plugin': ^3.10.1
  '@typescript-eslint/parser': ^3.10.1
  babel-eslint: ^10.1.0
  eslint: ^7.11.0
  eslint-config-prettier: ^6.11.0
  eslint-plugin-import: ^2.21.1
  eslint-plugin-jsx-a11y: ^6.2.3
  eslint-plugin-prettier: ^3.1.3
  eslint-plugin-react: ^7.20.0
  eslint-plugin-testing-library: ^1.5.0
  prettier: ^2.0.5
  typescript: ^4.0.2
