name: eds
engines:
  pnpm: '>=4'
scripts:
  lint: 'eslint ./libraries/**/*.{jsx,js}'
  init: pnpm multi install --force && pnpm run build
  build: pnpm --filter @equinor/eds-core-react run build
  'bump:core-react': >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm version
    prerelease
  'publish:core-react': >-
    pnpm --filter @equinor/eds-core-react recursive exec -- pnpm publish --tag
    alpha --access public
  storybook-build: >-
    pnpm --filter @equinor/eds-core-react install && pnpm --filter
    @equinor/eds-core-react run build && pnpm --filter
    @equinor/eds-storybook-react install && pnpm --filter
    @equinor/eds-storybook-react run build
  storybook-run: pnpm --filter @equinor/eds-storybook-react run start
  dockerize-storybook: docker build -t eds/storybook-react -f apps/storybook-react/Dockerfile.dev .
  storybook-docker-run: 'docker run -p 8080:80 eds/storybook-react'
  storybook-docker-inspect: docker run -it eds/storybook-react /bin/sh
  dockerize-storefront: docker build --build-arg GATSBY_STAGE=prod -t eds/storefront -f apps/storefront/Dockerfile .
  storefront-docker-run: 'docker run -p 8080:80 eds/storefront'
  storefront-docker-inspect: docker run -it eds/storefront /bin/sh
devDependencies:
  eslint: ^6.7.2
  eslint-config-airbnb: ^17.1.1
  eslint-config-prettier: ^6.7.0
  eslint-plugin-import: ^2.19.1
  eslint-plugin-jsx-a11y: ^6.2.3
  eslint-plugin-prettier: ^3.1.2
  eslint-plugin-react: ^7.17.0
  eslint-plugin-testing-library: ^1.3.4
  prettier: ^1.19.1
