// Auto-generated by Tokens Studio – do not edit manually.

export const theme = {
  accent: {
    '1': 'color(srgb 0.0907 0.1021 0.1033)',
    '2': 'color(srgb 0.0993 0.1125 0.1139)',
    '3': 'color(srgb 0.2354 0.385 0.4013)',
    '4': 'color(srgb 0.1543 0.1865 0.19)',
    '5': 'color(srgb 0.2303 0.3599 0.374)',
    '6': 'color(srgb 0.2582 0.5475 0.5779)',
    '7': 'color(srgb 0.2638 0.5671 0.5988)',
    '8': 'color(srgb 0.4326 0.7544 0.789)',
    '9': 'color(srgb 0.5488 0.8234 0.8534)',
    '10': 'color(srgb 0.6748 0.8901 0.9136)',
    '11': 'color(srgb 0.78 0.9452 0.9631)',
    '12': 'color(srgb 0.8415 0.9786 0.9934)',
    '13': 'color(srgb 0.9011 1.0125 1.0245)',
    '14': 'color(srgb 0.1742 0.2188 0.2236)',
    '15': 'color(srgb 0.0122 0.0132 0.0133)',
  },
  background: {
    backdrop: 'color(srgb 0.4498 0.5252 0.5871)',
    canvas: 'color(srgb 0.0967 0.1 0.1028)',
    dialog: 'color(srgb 0.0127 0.013 0.0132)',
    floating: 'color(srgb 0.0127 0.013 0.0132)',
    input: 'color(srgb 0.0967 0.1 0.1028)',
    interactive: {
      accent: {
        emphasis: {
          default: 'color(srgb 0.5488 0.8234 0.8534)',
          hover: 'color(srgb 0.6748 0.8901 0.9136)',
          pressed: 'color(srgb 0.78 0.9452 0.9631)',
        },
        muted: {
          default: 'color(srgb 0.0907 0.1021 0.1033)',
          hover: 'color(srgb 0.0993 0.1125 0.1139)',
          pressed: 'color(srgb 0.2354 0.385 0.4013)',
        },
        selected: {
          default: 'color(srgb 0.2303 0.3599 0.374)',
          hover: 'color(srgb 0.2638 0.5671 0.5988)',
          pressed: 'color(srgb 0.4326 0.7544 0.789)',
        },
      },
      danger: {
        emphasis: {
          default: 'color(srgb 1.1764 0.5369 0.5495)',
          hover: 'color(srgb 1.19 0.6735 0.6697)',
          pressed: 'color(srgb 1.1903 0.783 0.7732)',
        },
        muted: {
          default: 'color(srgb 0.1209 0.0913 0.09)',
          hover: 'color(srgb 0.1341 0.0999 0.0984)',
          pressed: 'color(srgb 0.5725 0.2269 0.2372)',
        },
      },
      disabled: 'color(srgb 0.1062 0.1101 0.1133)',
      info: {
        emphasis: {
          default: 'color(srgb 0.4883 0.8064 1.0297)',
          hover: 'color(srgb 0.6301 0.878 1.0586)',
          pressed: 'color(srgb 0.7468 0.9368 1.0781)',
        },
        muted: {
          default: 'color(srgb 0.0885 0.1017 0.1117)',
          hover: 'color(srgb 0.0967 0.1119 0.1235)',
          pressed: 'color(srgb 0.2016 0.3755 0.4959)',
        },
      },
      neutral: {
        emphasis: {
          default: 'color(srgb 0.7056 0.7801 0.8417)',
          hover: 'color(srgb 0.7938 0.8541 0.9041)',
          pressed: 'color(srgb 0.8692 0.9164 0.9557)',
        },
        muted: {
          default: 'color(srgb 0.0967 0.1 0.1028)',
          hover: 'color(srgb 0.1062 0.1101 0.1133)',
          pressed: 'color(srgb 0.3218 0.3619 0.395)',
        },
        selected: {
          default: 'color(srgb 0.2354 0.385 0.4013)',
          hover: 'color(srgb 0.1543 0.1865 0.19)',
          pressed: 'color(srgb 0.2303 0.3599 0.374)',
        },
      },
      readOnly: 'color(srgb 0.1062 0.1101 0.1133)',
      success: {
        emphasis: {
          default: 'color(srgb 0.5491 0.859 0.5312)',
          hover: 'color(srgb 0.6749 0.9204 0.6577)',
          pressed: 'color(srgb 0.78 0.9699 0.7652)',
        },
        muted: {
          default: 'color(srgb 0.0907 0.104 0.0895)',
          hover: 'color(srgb 0.0993 0.1146 0.0979)',
          pressed: 'color(srgb 0.2357 0.4039 0.2266)',
        },
      },
      warning: {
        emphasis: {
          default: 'color(srgb 1.0261 0.6773 0.3888)',
          hover: 'color(srgb 1.0592 0.7758 0.5542)',
          pressed: 'color(srgb 1.081 0.8579 0.6882)',
        },
        muted: {
          default: 'color(srgb 0.1122 0.0962 0.0844)',
          hover: 'color(srgb 0.124 0.1056 0.0919)',
          pressed: 'color(srgb 0.4932 0.3055 0.1461)',
        },
      },
    },
    inverted: 'color(srgb 0.9147 0.9542 0.9871)',
    nonInteractive: {
      accent: {
        /** Static status surface — medium emphasis, non-clickable. */
        default: 'color(srgb 0.2354 0.385 0.4013)',
        /** Static status surface — high emphasis (bold fill). Fill lightness inverts between light/dark schemes. */
        emphasis: 'color(srgb 0.5488 0.8234 0.8534)',
        /** Static status surface — low emphasis, non-clickable. */
        muted: 'color(srgb 0.0907 0.1021 0.1033)',
      },
      danger: {
        /** Static status surface — medium emphasis, non-clickable. */
        default: 'color(srgb 0.5725 0.2269 0.2372)',
        /** Static status surface — high emphasis (bold fill). Fill lightness inverts between light/dark schemes. */
        emphasis: 'color(srgb 1.1764 0.5369 0.5495)',
        /** Static status surface — low emphasis, non-clickable. */
        muted: 'color(srgb 0.1209 0.0913 0.09)',
      },
      info: {
        /** Static status surface — medium emphasis, non-clickable. */
        default: 'color(srgb 0.2016 0.3755 0.4959)',
        /** Static status surface — high emphasis (bold fill). Fill lightness inverts between light/dark schemes. */
        emphasis: 'color(srgb 0.4883 0.8064 1.0297)',
        /** Static status surface — low emphasis, non-clickable. */
        muted: 'color(srgb 0.0885 0.1017 0.1117)',
      },
      neutral: {
        /** Static status surface — medium emphasis, non-clickable. */
        default: 'color(srgb 0.3218 0.3619 0.395)',
        /** Static status surface — high emphasis (bold fill). Fill lightness inverts between light/dark schemes. */
        emphasis: 'color(srgb 0.7056 0.7801 0.8417)',
        /** Static status surface — low emphasis, non-clickable. */
        muted: 'color(srgb 0.0967 0.1 0.1028)',
      },
      success: {
        /** Static status surface — medium emphasis, non-clickable. */
        default: 'color(srgb 0.2357 0.4039 0.2266)',
        /** Static status surface — high emphasis (bold fill). Fill lightness inverts between light/dark schemes. */
        emphasis: 'color(srgb 0.5491 0.859 0.5312)',
        /** Static status surface — low emphasis, non-clickable. */
        muted: 'color(srgb 0.0907 0.104 0.0895)',
      },
      warning: {
        /** Static status surface — medium emphasis, non-clickable. */
        default: 'color(srgb 0.4932 0.3055 0.1461)',
        /** Static status surface — high emphasis (bold fill). Fill lightness inverts between light/dark schemes. */
        emphasis: 'color(srgb 1.0261 0.6773 0.3888)',
        /** Static status surface — low emphasis, non-clickable. */
        muted: 'color(srgb 0.1122 0.0962 0.0844)',
      },
    },
    surface: 'color(srgb 0.0127 0.013 0.0132)',
  },
  border: {
    interactive: {
      accent: {
        emphasis: {
          default: 'color(srgb 0.5488 0.8234 0.8534)',
          hover: 'color(srgb 0.6748 0.8901 0.9136)',
          pressed: 'color(srgb 0.78 0.9452 0.9631)',
        },
        muted: {
          default: 'color(srgb 0.1543 0.1865 0.19)',
          hover: 'color(srgb 0.2303 0.3599 0.374)',
          pressed: 'color(srgb 0.2638 0.5671 0.5988)',
        },
      },
      danger: {
        emphasis: {
          default: 'color(srgb 1.1764 0.5369 0.5495)',
          hover: 'color(srgb 1.19 0.6735 0.6697)',
          pressed: 'color(srgb 1.1903 0.783 0.7732)',
        },
        muted: {
          default: 'color(srgb 0.2361 0.1552 0.1526)',
          hover: 'color(srgb 0.5264 0.2248 0.2307)',
          pressed: 'color(srgb 0.8998 0.2156 0.2837)',
        },
      },
      disabled: 'color(srgb 0.1715 0.1808 0.1886)',
      focus: 'color(srgb 0.1765 0.5459 0.7733)',
      info: {
        emphasis: {
          default: 'color(srgb 0.4883 0.8064 1.0297)',
          hover: 'color(srgb 0.6301 0.878 1.0586)',
          pressed: 'color(srgb 0.7468 0.9368 1.0781)',
        },
        muted: {
          default: 'color(srgb 0.1478 0.185 0.2129)',
          hover: 'color(srgb 0.2018 0.3518 0.4572)',
          pressed: 'color(srgb 0.1765 0.5459 0.7733)',
        },
      },
      link: {
        default: 'color(srgb 0.3547 0.7329 0.9853)',
        hover: 'color(srgb 0.4883 0.8064 1.0297)',
        pressed: 'color(srgb 0.6301 0.878 1.0586)',
      },
      neutral: {
        emphasis: {
          default: 'color(srgb 0.7056 0.7801 0.8417)',
          hover: 'color(srgb 0.7938 0.8541 0.9041)',
          pressed: 'color(srgb 0.8692 0.9164 0.9557)',
        },
        muted: {
          default: 'color(srgb 0.1715 0.1808 0.1886)',
          hover: 'color(srgb 0.3043 0.3395 0.3685)',
          pressed: 'color(srgb 0.4498 0.5252 0.5871)',
        },
      },
      selectedIndicator: 'color(srgb 0.9011 1.0125 1.0245)',
      success: {
        emphasis: {
          default: 'color(srgb 0.5491 0.859 0.5312)',
          hover: 'color(srgb 0.6749 0.9204 0.6577)',
          pressed: 'color(srgb 0.78 0.9699 0.7652)',
        },
        muted: {
          default: 'color(srgb 0.1542 0.1915 0.1512)',
          hover: 'color(srgb 0.2305 0.3767 0.222)',
          pressed: 'color(srgb 0.2647 0.6002 0.2548)',
        },
      },
      warning: {
        emphasis: {
          default: 'color(srgb 1.0261 0.6773 0.3888)',
          hover: 'color(srgb 1.0592 0.7758 0.5542)',
          pressed: 'color(srgb 1.081 0.8579 0.6882)',
        },
        muted: {
          default: 'color(srgb 0.2137 0.1696 0.1363)',
          hover: 'color(srgb 0.4555 0.291 0.1549)',
          pressed: 'color(srgb 0.7629 0.4089 -0.0544)',
        },
      },
    },
    nonInteractive: {
      accent: {
        /** Default border emphasis. */
        default: 'color(srgb 0.2638 0.5671 0.5988)',
        /** High-emphasis border — strong outline / bold state. */
        emphasis: 'color(srgb 0.5488 0.8234 0.8534)',
        /** Low-emphasis border — dividers, quiet outlines. */
        muted: 'color(srgb 0.1543 0.1865 0.19)',
      },
      danger: {
        /** Default border emphasis. */
        default: 'color(srgb 0.8998 0.2156 0.2837)',
        /** High-emphasis border — strong outline / bold state. */
        emphasis: 'color(srgb 1.1764 0.5369 0.5495)',
        /** Low-emphasis border — dividers, quiet outlines. */
        muted: 'color(srgb 0.2361 0.1552 0.1526)',
      },
      info: {
        /** Default border emphasis. */
        default: 'color(srgb 0.1765 0.5459 0.7733)',
        /** High-emphasis border — strong outline / bold state. */
        emphasis: 'color(srgb 0.4883 0.8064 1.0297)',
        /** Low-emphasis border — dividers, quiet outlines. */
        muted: 'color(srgb 0.1478 0.185 0.2129)',
      },
      neutral: {
        /** Default border emphasis. */
        default: 'color(srgb 0.4498 0.5252 0.5871)',
        /** High-emphasis border — strong outline / bold state. */
        emphasis: 'color(srgb 0.7056 0.7801 0.8417)',
        /** Low-emphasis border — dividers, quiet outlines. */
        muted: 'color(srgb 0.1715 0.1808 0.1886)',
      },
      success: {
        /** Default border emphasis. */
        default: 'color(srgb 0.2647 0.6002 0.2548)',
        /** High-emphasis border — strong outline / bold state. */
        emphasis: 'color(srgb 0.5491 0.859 0.5312)',
        /** Low-emphasis border — dividers, quiet outlines. */
        muted: 'color(srgb 0.1542 0.1915 0.1512)',
      },
      warning: {
        /** Default border emphasis. */
        default: 'color(srgb 0.7629 0.4089 -0.0544)',
        /** High-emphasis border — strong outline / bold state. */
        emphasis: 'color(srgb 1.0261 0.6773 0.3888)',
        /** Low-emphasis border — dividers, quiet outlines. */
        muted: 'color(srgb 0.2137 0.1696 0.1363)',
      },
    },
  },
  cornerRadius: {
    none: '0px',
    pill: '9999px',
    rounded: '4px',
    roundedOuter: '5px',
  },
  danger: {
    '1': 'color(srgb 0.1209 0.0913 0.09)',
    '2': 'color(srgb 0.1341 0.0999 0.0984)',
    '3': 'color(srgb 0.5725 0.2269 0.2372)',
    '4': 'color(srgb 0.2361 0.1552 0.1526)',
    '5': 'color(srgb 0.5264 0.2248 0.2307)',
    '6': 'color(srgb 0.867 0.2143 0.2763)',
    '7': 'color(srgb 0.8998 0.2156 0.2837)',
    '8': 'color(srgb 1.1371 0.4037 0.4428)',
    '9': 'color(srgb 1.1764 0.5369 0.5495)',
    '10': 'color(srgb 1.19 0.6735 0.6697)',
    '11': 'color(srgb 1.1903 0.783 0.7732)',
    '12': 'color(srgb 1.1892 0.8456 0.8346)',
    '13': 'color(srgb 1.1893 0.9055 0.8947)',
    '14': 'color(srgb 0.2851 0.1751 0.1723)',
    '15': 'color(srgb 0.015 0.0122 0.0121)',
  },
  dark: {
    blue: {
      '1': 'color(srgb 0.0885 0.1017 0.1117)',
      '2': 'color(srgb 0.0967 0.1119 0.1235)',
      '3': 'color(srgb 0.2016 0.3755 0.4959)',
      '4': 'color(srgb 0.1478 0.185 0.2129)',
      '5': 'color(srgb 0.2018 0.3518 0.4572)',
      '6': 'color(srgb 0.1766 0.5274 0.7451)',
      '7': 'color(srgb 0.1765 0.5459 0.7733)',
      '8': 'color(srgb 0.3547 0.7329 0.9853)',
      '9': 'color(srgb 0.4883 0.8064 1.0297)',
      '10': 'color(srgb 0.6301 0.878 1.0586)',
      '11': 'color(srgb 0.7468 0.9368 1.0781)',
      '12': 'color(srgb 0.8143 0.972 1.0904)',
      '13': 'color(srgb 0.8792 1.0075 1.1045)',
      '14': 'color(srgb 0.1653 0.2165 0.2547)',
      '15': 'color(srgb 0.012 0.0131 0.0141)',
    },
    dataviz: {
      cat: {
        '1': {
          '1': '#00282c',
          '2': '#00383c',
          '3': '#03484c',
          '4': '#5d8386',
          '5': '#adc3c4',
        },
        '2': {
          '1': '#544100',
          '2': '#a28200',
          '3': '#f4cb00',
          '4': '#f7db79',
          '5': '#f9eab5',
        },
        '3': {
          '1': '#003f6e',
          '2': '#0078b7',
          '3': '#4bb6fc',
          '4': '#8aceff',
          '5': '#e0c9ee',
        },
        '4': {
          '1': '#5e053e',
          '2': '#92376a',
          '3': '#c86499',
          '4': '#df96ba',
          '5': '#f4c8dc',
        },
        '5': {
          '1': '#153900',
          '2': '#315f00',
          '3': '#548723',
          '4': '#8ab06f',
          '5': '#c2d9b3',
        },
        '6': {
          '1': '#410a55',
          '2': '#622c79',
          '3': '#854b9e',
          '4': '#af86c2',
          '5': '#d9c1e5',
        },
        '7': {
          '1': '#590009',
          '2': '#7e1823',
          '3': '#a3383e',
          '4': '#ca7b7a',
          '5': '#edbcba',
        },
        '8': {
          '1': '#00432b',
          '2': '#007853',
          '3': '#00ad81',
          '4': '#75c9a8',
          '5': '#b7e5d1',
        },
        '9': {
          '1': '#052a70',
          '2': '#2a53a0',
          '3': '#507ed3',
          '4': '#87a9e7',
          '5': '#bfd4f9',
        },
        '10': {
          '1': '#671f00',
          '2': '#aa5215',
          '3': '#ed8b52',
          '4': '#f7b18a',
          '5': '#ffd5bf',
        },
      },
      div: {
        '1': '#539cec',
        '2': '#4579b2',
        '3': '#38577b',
        '4': '#2a3848',
        '5': '#1b1b1b',
        '6': '#443224',
        '7': '#724b2c',
        '8': '#a36530',
        '9': '#d78031',
      },
      seq: {
        '1': '#243032',
        '2': '#2a4f54',
        '3': '#14727b',
        '4': '#0096a4',
        '5': '#00b9c9',
        '6': '#5dd8e5',
        '7': '#acf3fb',
      },
    },
    gray: {
      '1': 'color(srgb 0.0995 0.0995 0.0995)',
      '2': 'color(srgb 0.1094 0.1094 0.1094)',
      '3': 'color(srgb 0.3556 0.3556 0.3556)',
      '4': 'color(srgb 0.1792 0.1792 0.1792)',
      '5': 'color(srgb 0.3338 0.3338 0.3338)',
      '6': 'color(srgb 0.4963 0.4963 0.4963)',
      '7': 'color(srgb 0.5137 0.5137 0.5137)',
      '8': 'color(srgb 0.6936 0.6936 0.6936)',
      '9': 'color(srgb 0.7682 0.7682 0.7682)',
      '10': 'color(srgb 0.8442 0.8442 0.8442)',
      '11': 'color(srgb 0.9085 0.9085 0.9085)',
      '12': 'color(srgb 0.9475 0.9475 0.9475)',
      '13': 'color(srgb 0.9868 0.9868 0.9868)',
      '14': 'color(srgb 0.2089 0.2089 0.2089)',
      '15': 'color(srgb 0.0129 0.0129 0.0129)',
    },
    green: {
      '1': 'color(srgb 0.0907 0.104 0.0895)',
      '2': 'color(srgb 0.0993 0.1146 0.0979)',
      '3': 'color(srgb 0.2357 0.4039 0.2266)',
      '4': 'color(srgb 0.1542 0.1915 0.1512)',
      '5': 'color(srgb 0.2305 0.3767 0.222)',
      '6': 'color(srgb 0.2591 0.5793 0.2493)',
      '7': 'color(srgb 0.2647 0.6002 0.2548)',
      '8': 'color(srgb 0.4333 0.7928 0.4173)',
      '9': 'color(srgb 0.5491 0.859 0.5312)',
      '10': 'color(srgb 0.6749 0.9204 0.6577)',
      '11': 'color(srgb 0.78 0.9699 0.7652)',
      '12': 'color(srgb 0.8415 0.9997 0.8284)',
      '13': 'color(srgb 0.901 1.0302 0.89)',
      '14': 'color(srgb 0.1742 0.2255 0.1702)',
      '15': 'color(srgb 0.0122 0.0133 0.012)',
    },
    mossGreen: {
      '1': 'color(srgb 0.0907 0.1021 0.1033)',
      '2': 'color(srgb 0.0993 0.1125 0.1139)',
      '3': 'color(srgb 0.2354 0.385 0.4013)',
      '4': 'color(srgb 0.1543 0.1865 0.19)',
      '5': 'color(srgb 0.2303 0.3599 0.374)',
      '6': 'color(srgb 0.2582 0.5475 0.5779)',
      '7': 'color(srgb 0.2638 0.5671 0.5988)',
      '8': 'color(srgb 0.4326 0.7544 0.789)',
      '9': 'color(srgb 0.5488 0.8234 0.8534)',
      '10': 'color(srgb 0.6748 0.8901 0.9136)',
      '11': 'color(srgb 0.78 0.9452 0.9631)',
      '12': 'color(srgb 0.8415 0.9786 0.9934)',
      '13': 'color(srgb 0.9011 1.0125 1.0245)',
      '14': 'color(srgb 0.1742 0.2188 0.2236)',
      '15': 'color(srgb 0.0122 0.0132 0.0133)',
    },
    northSea: {
      '1': 'color(srgb 0.0967 0.1 0.1028)',
      '2': 'color(srgb 0.1062 0.1101 0.1133)',
      '3': 'color(srgb 0.3218 0.3619 0.395)',
      '4': 'color(srgb 0.1715 0.1808 0.1886)',
      '5': 'color(srgb 0.3043 0.3395 0.3685)',
      '6': 'color(srgb 0.4351 0.5073 0.5666)',
      '7': 'color(srgb 0.4498 0.5252 0.5871)',
      '8': 'color(srgb 0.6227 0.7067 0.7758)',
      '9': 'color(srgb 0.7056 0.7801 0.8417)',
      '10': 'color(srgb 0.7938 0.8541 0.9041)',
      '11': 'color(srgb 0.8692 0.9164 0.9557)',
      '12': 'color(srgb 0.9147 0.9542 0.9871)',
      '13': 'color(srgb 0.96 0.9923 1.0194)',
      '14': 'color(srgb 0.1983 0.211 0.2216)',
      '15': 'color(srgb 0.0127 0.013 0.0132)',
    },
    orange: {
      '1': 'color(srgb 0.1122 0.0962 0.0844)',
      '2': 'color(srgb 0.124 0.1056 0.0919)',
      '3': 'color(srgb 0.4932 0.3055 0.1461)',
      '4': 'color(srgb 0.2137 0.1696 0.1363)',
      '5': 'color(srgb 0.4555 0.291 0.1549)',
      '6': 'color(srgb 0.7353 0.3963 -0.0285)',
      '7': 'color(srgb 0.7629 0.4089 -0.0544)',
      '8': 'color(srgb 0.9771 0.5841 0.2228)',
      '9': 'color(srgb 1.0261 0.6773 0.3888)',
      '10': 'color(srgb 1.0592 0.7758 0.5542)',
      '11': 'color(srgb 1.081 0.8579 0.6882)',
      '12': 'color(srgb 1.094 0.9064 0.7654)',
      '13': 'color(srgb 1.1083 0.9541 0.8391)',
      '14': 'color(srgb 0.2555 0.1952 0.1494)',
      '15': 'color(srgb 0.0141 0.0126 0.0116)',
    },
    red: {
      '1': 'color(srgb 0.1209 0.0913 0.09)',
      '2': 'color(srgb 0.1341 0.0999 0.0984)',
      '3': 'color(srgb 0.5725 0.2269 0.2372)',
      '4': 'color(srgb 0.2361 0.1552 0.1526)',
      '5': 'color(srgb 0.5264 0.2248 0.2307)',
      '6': 'color(srgb 0.867 0.2143 0.2763)',
      '7': 'color(srgb 0.8998 0.2156 0.2837)',
      '8': 'color(srgb 1.1371 0.4037 0.4428)',
      '9': 'color(srgb 1.1764 0.5369 0.5495)',
      '10': 'color(srgb 1.19 0.6735 0.6697)',
      '11': 'color(srgb 1.1903 0.783 0.7732)',
      '12': 'color(srgb 1.1892 0.8456 0.8346)',
      '13': 'color(srgb 1.1893 0.9055 0.8947)',
      '14': 'color(srgb 0.2851 0.1751 0.1723)',
      '15': 'color(srgb 0.015 0.0122 0.0121)',
    },
  },
  dataVisualization: {
    cat: {
      '1': {
        '1': '#00282c',
        '2': '#00383c',
        '3': '#03484c',
        '4': '#5d8386',
        '5': '#adc3c4',
      },
      '2': {
        '1': '#544100',
        '2': '#a28200',
        '3': '#f4cb00',
        '4': '#f7db79',
        '5': '#f9eab5',
      },
      '3': {
        '1': '#003f6e',
        '2': '#0078b7',
        '3': '#4bb6fc',
        '4': '#8aceff',
        '5': '#e0c9ee',
      },
      '4': {
        '1': '#5e053e',
        '2': '#92376a',
        '3': '#c86499',
        '4': '#df96ba',
        '5': '#f4c8dc',
      },
      '5': {
        '1': '#153900',
        '2': '#315f00',
        '3': '#548723',
        '4': '#8ab06f',
        '5': '#c2d9b3',
      },
      '6': {
        '1': '#410a55',
        '2': '#622c79',
        '3': '#854b9e',
        '4': '#af86c2',
        '5': '#d9c1e5',
      },
      '7': {
        '1': '#590009',
        '2': '#7e1823',
        '3': '#a3383e',
        '4': '#ca7b7a',
        '5': '#edbcba',
      },
      '8': {
        '1': '#00432b',
        '2': '#007853',
        '3': '#00ad81',
        '4': '#75c9a8',
        '5': '#b7e5d1',
      },
      '9': {
        '1': '#052a70',
        '2': '#2a53a0',
        '3': '#507ed3',
        '4': '#87a9e7',
        '5': '#bfd4f9',
      },
      '10': {
        '1': '#671f00',
        '2': '#aa5215',
        '3': '#ed8b52',
        '4': '#f7b18a',
        '5': '#ffd5bf',
      },
    },
    div: {
      '1': '#539cec',
      '2': '#4579b2',
      '3': '#38577b',
      '4': '#2a3848',
      '5': '#1b1b1b',
      '6': '#443224',
      '7': '#724b2c',
      '8': '#a36530',
      '9': '#d78031',
    },
    seq: {
      '1': '#243032',
      '2': '#2a4f54',
      '3': '#14727b',
      '4': '#0096a4',
      '5': '#00b9c9',
      '6': '#5dd8e5',
      '7': '#acf3fb',
    },
  },
  dataviz: {
    cat: {
      '1': {
        '1': '#00282c',
        '2': '#00383c',
        '3': '#03484c',
        '4': '#5d8386',
        '5': '#adc3c4',
      },
      '2': {
        '1': '#544100',
        '2': '#a28200',
        '3': '#f4cb00',
        '4': '#f7db79',
        '5': '#f9eab5',
      },
      '3': {
        '1': '#003f6e',
        '2': '#0078b7',
        '3': '#4bb6fc',
        '4': '#8aceff',
        '5': '#e0c9ee',
      },
      '4': {
        '1': '#5e053e',
        '2': '#92376a',
        '3': '#c86499',
        '4': '#df96ba',
        '5': '#f4c8dc',
      },
      '5': {
        '1': '#153900',
        '2': '#315f00',
        '3': '#548723',
        '4': '#8ab06f',
        '5': '#c2d9b3',
      },
      '6': {
        '1': '#410a55',
        '2': '#622c79',
        '3': '#854b9e',
        '4': '#af86c2',
        '5': '#d9c1e5',
      },
      '7': {
        '1': '#590009',
        '2': '#7e1823',
        '3': '#a3383e',
        '4': '#ca7b7a',
        '5': '#edbcba',
      },
      '8': {
        '1': '#00432b',
        '2': '#007853',
        '3': '#00ad81',
        '4': '#75c9a8',
        '5': '#b7e5d1',
      },
      '9': {
        '1': '#052a70',
        '2': '#2a53a0',
        '3': '#507ed3',
        '4': '#87a9e7',
        '5': '#bfd4f9',
      },
      '10': {
        '1': '#671f00',
        '2': '#aa5215',
        '3': '#ed8b52',
        '4': '#f7b18a',
        '5': '#ffd5bf',
      },
    },
    div: {
      '1': '#539cec',
      '2': '#4579b2',
      '3': '#38577b',
      '4': '#2a3848',
      '5': '#1b1b1b',
      '6': '#443224',
      '7': '#724b2c',
      '8': '#a36530',
      '9': '#d78031',
    },
    seq: {
      '1': '#243032',
      '2': '#2a4f54',
      '3': '#14727b',
      '4': '#0096a4',
      '5': '#00b9c9',
      '6': '#5dd8e5',
      '7': '#acf3fb',
    },
  },
  density: {
    cornerRadius: {
      none: '0px',
      pill: '9999px',
      rounded: '4px',
      roundedOuter: '5px',
    },
    spacing: {
      '2xl': '28px',
      '2xs': '6px',
      '3xl': '32px',
      '3xs': '4px',
      '4xs': '2px',
      lg: '20px',
      md: '16px',
      none: '0px',
      sm: '12px',
      xl: '24px',
      xs: '8px',
    },
    typography: {
      header: {
        '2xl': {
          fontSize: '24px',
          lineHeight: '28px',
        },
        '3xl': {
          fontSize: '28px',
          lineHeight: '32px',
        },
        '4xl': {
          fontSize: '32px',
          lineHeight: '36px',
        },
        lg: {
          fontSize: '18px',
          lineHeight: '24px',
        },
        md: {
          fontSize: '16px',
          lineHeight: '20px',
        },
        sm: {
          fontSize: '14px',
          lineHeight: '16px',
        },
        xl: {
          fontSize: '21px',
          lineHeight: '24px',
        },
        xs: {
          fontSize: '12px',
          lineHeight: '16px',
        },
      },
      ui: {
        '2xl': {
          fontSize: '21px',
          lineHeight: '28px',
        },
        '3xl': {
          fontSize: '24px',
          lineHeight: '32px',
        },
        '4xl': {
          fontSize: '28px',
          lineHeight: '32px',
        },
        '5xl': {
          fontSize: '32px',
          lineHeight: '36px',
        },
        lg: {
          fontSize: '16px',
          lineHeight: '24px',
        },
        md: {
          fontSize: '14px',
          lineHeight: '20px',
        },
        sm: {
          fontSize: '12px',
          lineHeight: '16px',
        },
        xl: {
          fontSize: '18px',
          lineHeight: '24px',
        },
        xs: {
          fontSize: '10px',
          lineHeight: '16px',
        },
      },
    },
  },
  elevation: {
    /** Ambient (diffuse) shadow colour for the light scheme. From Figma '🌗 Color scheme/elevation-ambient'. */
    ambient: 'color(srgb 0 0 0 / 0.12)',
    /** High elevation — two-layer (key + ambient) shadow. Semantic face over the shadow.* parts in elevation/default, mirroring how spacing.* faces density.spacing.*. */
    high: '0px 4px 12px 0px color(srgb 0 0 0 / 0.2), 0px 12px 16px 6px color(srgb 0 0 0 / 0.12)',
    /** Key (direct) shadow colour for the light scheme. From Figma '🌗 Color scheme/elevation-key'. */
    key: 'color(srgb 0 0 0 / 0.2)',
    /** Low elevation — two-layer (key + ambient) shadow. Semantic face over the shadow.* parts in elevation/default, mirroring how spacing.* faces density.spacing.*. */
    low: '0px 1px 8px 0px color(srgb 0 0 0 / 0.2), 0px 4px 8px 3px color(srgb 0 0 0 / 0.12)',
  },
  family: {
    header: 'Equinor',
    ui: 'Inter',
  },
  fontFamily: {
    header: 'Equinor',
    ui: 'Inter',
  },
  fontWeight: {
    bolder: '500',
    lighter: '300',
    normal: '400',
  },
  icon: {
    interactive: {
      accent: {
        default: 'color(srgb 0.78 0.9452 0.9631)',
        hover: 'color(srgb 0.8415 0.9786 0.9934)',
        pressed: 'color(srgb 0.9011 1.0125 1.0245)',
      },
      danger: {
        default: 'color(srgb 1.1903 0.783 0.7732)',
        hover: 'color(srgb 1.1892 0.8456 0.8346)',
        pressed: 'color(srgb 1.1893 0.9055 0.8947)',
      },
      disabled: 'color(srgb 0.4498 0.5252 0.5871)',
      info: {
        default: 'color(srgb 0.7468 0.9368 1.0781)',
        hover: 'color(srgb 0.8143 0.972 1.0904)',
        pressed: 'color(srgb 0.8792 1.0075 1.1045)',
      },
      link: {
        default: 'color(srgb 0.3547 0.7329 0.9853)',
        hover: 'color(srgb 0.4883 0.8064 1.0297)',
        pressed: 'color(srgb 0.6301 0.878 1.0586)',
      },
      success: {
        default: 'color(srgb 0.78 0.9699 0.7652)',
        hover: 'color(srgb 0.8415 0.9997 0.8284)',
        pressed: 'color(srgb 0.901 1.0302 0.89)',
      },
      warning: {
        default: 'color(srgb 1.081 0.8579 0.6882)',
        hover: 'color(srgb 1.094 0.9064 0.7654)',
        pressed: 'color(srgb 1.1083 0.9541 0.8391)',
      },
    },
    inverted: 'color(srgb 0.0967 0.1 0.1028)',
    onDefault: {
      accent: 'color(srgb 0.6748 0.8901 0.9136)',
      danger: 'color(srgb 1.19 0.6735 0.6697)',
      info: 'color(srgb 0.6301 0.878 1.0586)',
      neutral: 'color(srgb 0.7938 0.8541 0.9041)',
      success: 'color(srgb 0.6749 0.9204 0.6577)',
      warning: 'color(srgb 1.0592 0.7758 0.5542)',
    },
    onEmphasis: {
      accent: 'color(srgb 0.0122 0.0132 0.0133)',
      danger: 'color(srgb 0.015 0.0122 0.0121)',
      info: 'color(srgb 0.012 0.0131 0.0141)',
      neutral: 'color(srgb 0.0127 0.013 0.0132)',
      success: 'color(srgb 0.0122 0.0133 0.012)',
      warning: 'color(srgb 0.0141 0.0126 0.0116)',
    },
    onMuted: {
      accent: 'color(srgb 0.8415 0.9786 0.9934)',
      danger: 'color(srgb 1.1892 0.8456 0.8346)',
      info: 'color(srgb 0.8143 0.972 1.0904)',
      neutral: 'color(srgb 0.9147 0.9542 0.9871)',
      success: 'color(srgb 0.8415 0.9997 0.8284)',
      warning: 'color(srgb 1.094 0.9064 0.7654)',
    },
    primary: 'color(srgb 0.96 0.9923 1.0194)',
    secondary: 'color(srgb 0.6227 0.7067 0.7758)',
    tertiary: 'color(srgb 0.4498 0.5252 0.5871)',
  },
  info: {
    '1': 'color(srgb 0.0885 0.1017 0.1117)',
    '2': 'color(srgb 0.0967 0.1119 0.1235)',
    '3': 'color(srgb 0.2016 0.3755 0.4959)',
    '4': 'color(srgb 0.1478 0.185 0.2129)',
    '5': 'color(srgb 0.2018 0.3518 0.4572)',
    '6': 'color(srgb 0.1766 0.5274 0.7451)',
    '7': 'color(srgb 0.1765 0.5459 0.7733)',
    '8': 'color(srgb 0.3547 0.7329 0.9853)',
    '9': 'color(srgb 0.4883 0.8064 1.0297)',
    '10': 'color(srgb 0.6301 0.878 1.0586)',
    '11': 'color(srgb 0.7468 0.9368 1.0781)',
    '12': 'color(srgb 0.8143 0.972 1.0904)',
    '13': 'color(srgb 0.8792 1.0075 1.1045)',
    '14': 'color(srgb 0.1653 0.2165 0.2547)',
    '15': 'color(srgb 0.012 0.0131 0.0141)',
  },
  light: {
    blue: {
      '1': 'color(srgb 0.9245 0.9839 1.0295)',
      '2': 'color(srgb 0.8509 0.9356 1.0003)',
      '3': 'color(srgb 0.7923 0.9002 0.982)',
      '4': 'color(srgb 0.7095 0.8537 0.9619)',
      '5': 'color(srgb 0.5991 0.7962 0.9413)',
      '6': 'color(srgb 0.4825 0.7385 0.9215)',
      '7': 'color(srgb 0.3623 0.6798 0.8968)',
      '8': 'color(srgb 0.1141 0.5592 0.8116)',
      '9': 'color(srgb -0.0615 0.4387 0.6641)',
      '10': 'color(srgb -0.0103 0.3799 0.5723)',
      '11': 'color(srgb 0.0558 0.3224 0.4758)',
      '12': 'color(srgb 0.0873 0.2662 0.3806)',
      '13': 'color(srgb 0.0949 0.2117 0.2914)',
      '14': 'color(srgb 0.7721 0.8885 0.9765)',
      '15': 'color(srgb 0.9595 1.0085 1.0462)',
    },
    dataviz: {
      cat: {
        '1': {
          '1': '#adc3c4',
          '2': '#5d8386',
          '3': '#03484c',
          '4': '#00383c',
          '5': '#00282c',
        },
        '2': {
          '1': '#f9eab5',
          '2': '#f7db79',
          '3': '#f4cb00',
          '4': '#a28200',
          '5': '#544100',
        },
        '3': {
          '1': '#c0e6ff',
          '2': '#8aceff',
          '3': '#4bb6fc',
          '4': '#0078b7',
          '5': '#003f6e',
        },
        '4': {
          '1': '#f4c8dc',
          '2': '#df96ba',
          '3': '#c86499',
          '4': '#92376a',
          '5': '#5e053e',
        },
        '5': {
          '1': '#c2d9b3',
          '2': '#8ab06f',
          '3': '#548723',
          '4': '#315f00',
          '5': '#153900',
        },
        '6': {
          '1': '#d9c1e5',
          '2': '#af86c2',
          '3': '#854b9e',
          '4': '#622c79',
          '5': '#410a55',
        },
        '7': {
          '1': '#edbcba',
          '2': '#ca7b7a',
          '3': '#a3383e',
          '4': '#7e1823',
          '5': '#590009',
        },
        '8': {
          '1': '#b7e5d1',
          '2': '#75c9a8',
          '3': '#00ad81',
          '4': '#007853',
          '5': '#00432b',
        },
        '9': {
          '1': '#bfd4f9',
          '2': '#87a9e7',
          '3': '#507ed3',
          '4': '#2a53a0',
          '5': '#052a70',
        },
        '10': {
          '1': '#ffd5bf',
          '2': '#f7b18a',
          '3': '#ed8b52',
          '4': '#aa5215',
          '5': '#671f00',
        },
      },
      div: {
        '1': '#1564b0',
        '2': '#5387c1',
        '3': '#87a9d2',
        '4': '#bacce1',
        '5': '#eeeeee',
        '6': '#dcc5b4',
        '7': '#c89c7a',
        '8': '#b2733f',
        '9': '#9b4900',
      },
      seq: {
        '1': '#dff7fa',
        '2': '#a4dbe2',
        '3': '#59c1cc',
        '4': '#00a4b3',
        '5': '#008290',
        '6': '#00626c',
        '7': '#054046',
      },
    },
    gray: {
      '1': 'color(srgb 0.9737 0.9737 0.9737)',
      '2': 'color(srgb 0.9215 0.9215 0.9215)',
      '3': 'color(srgb 0.8827 0.8827 0.8827)',
      '4': 'color(srgb 0.8314 0.8314 0.8314)',
      '5': 'color(srgb 0.7682 0.7682 0.7682)',
      '6': 'color(srgb 0.706 0.706 0.706)',
      '7': 'color(srgb 0.6447 0.6447 0.6447)',
      '8': 'color(srgb 0.5254 0.5254 0.5254)',
      '9': 'color(srgb 0.4109 0.4109 0.4109)',
      '10': 'color(srgb 0.3556 0.3556 0.3556)',
      '11': 'color(srgb 0.3017 0.3017 0.3017)',
      '12': 'color(srgb 0.2494 0.2494 0.2494)',
      '13': 'color(srgb 0.1989 0.1989 0.1989)',
      '14': 'color(srgb 0.8698 0.8698 0.8698)',
      '15': 'color(srgb 1 1 1)',
    },
    green: {
      '1': 'color(srgb 0.9344 0.9946 0.9289)',
      '2': 'color(srgb 0.8651 0.9508 0.8575)',
      '3': 'color(srgb 0.8106 0.9193 0.8012)',
      '4': 'color(srgb 0.7344 0.879 0.7226)',
      '5': 'color(srgb 0.6341 0.8303 0.6197)',
      '6': 'color(srgb 0.5302 0.7816 0.5142)',
      '7': 'color(srgb 0.4258 0.7311 0.4104)',
      '8': 'color(srgb 0.2371 0.6197 0.2298)',
      '9': 'color(srgb 0.1324 0.493 0.1325)',
      '10': 'color(srgb 0.1244 0.4262 0.1224)',
      '11': 'color(srgb 0.1276 0.3591 0.1228)',
      '12': 'color(srgb 0.1274 0.2935 0.1214)',
      '13': 'color(srgb 0.1183 0.2306 0.1128)',
      '14': 'color(srgb 0.7919 0.9091 0.7819)',
      '15': 'color(srgb 0.9676 1.0173 0.963)',
    },
    mossGreen: {
      '1': 'color(srgb 0.9345 0.9859 0.9914)',
      '2': 'color(srgb 0.8652 0.9387 0.9466)',
      '3': 'color(srgb 0.8107 0.9044 0.9144)',
      '4': 'color(srgb 0.7344 0.8598 0.8733)',
      '5': 'color(srgb 0.6341 0.8054 0.8241)',
      '6': 'color(srgb 0.53 0.7517 0.776)',
      '7': 'color(srgb 0.4253 0.6975 0.727)',
      '8': 'color(srgb 0.2357 0.5838 0.6194)',
      '9': 'color(srgb 0.1305 0.4619 0.4941)',
      '10': 'color(srgb 0.123 0.3994 0.4268)',
      '11': 'color(srgb 0.1268 0.3372 0.3588)',
      '12': 'color(srgb 0.127 0.2765 0.2924)',
      '13': 'color(srgb 0.1182 0.2183 0.2291)',
      '14': 'color(srgb 0.792 0.8931 0.904)',
      '15': 'color(srgb 0.9677 1.0102 1.0147)',
    },
    northSea: {
      '1': 'color(srgb 0.9612 0.9763 0.989)',
      '2': 'color(srgb 0.9037 0.9252 0.9432)',
      '3': 'color(srgb 0.8601 0.8873 0.9101)',
      '4': 'color(srgb 0.8015 0.8375 0.8676)',
      '5': 'color(srgb 0.7278 0.7762 0.8165)',
      '6': 'color(srgb 0.6548 0.7158 0.7664)',
      '7': 'color(srgb 0.5838 0.6561 0.7157)',
      '8': 'color(srgb 0.4543 0.538 0.6064)',
      '9': 'color(srgb 0.3473 0.4219 0.4826)',
      '10': 'color(srgb 0.3013 0.365 0.4169)',
      '11': 'color(srgb 0.2585 0.3094 0.3509)',
      '12': 'color(srgb 0.2173 0.2553 0.2865)',
      '13': 'color(srgb 0.1766 0.2031 0.2249)',
      '14': 'color(srgb 0.8455 0.8748 0.8993)',
      '15': 'color(srgb 0.9897 1.0022 1.0127)',
    },
    orange: {
      '1': 'color(srgb 1.0322 0.9592 0.9056)',
      '2': 'color(srgb 1.0035 0.9004 0.8242)',
      '3': 'color(srgb 0.9854 0.8553 0.7585)',
      '4': 'color(srgb 0.965 0.7938 0.6648)',
      '5': 'color(srgb 0.9429 0.7147 0.5386)',
      '6': 'color(srgb 0.92 0.6338 0.4037)',
      '7': 'color(srgb 0.8912 0.553 0.2585)',
      '8': 'color(srgb 0.7983 0.405 -0.2285)',
      '9': 'color(srgb 0.6501 0.298 -0.2629)',
      '10': 'color(srgb 0.5609 0.2606 -0.1659)',
      '11': 'color(srgb 0.4678 0.2288 -0.064)',
      '12': 'color(srgb 0.3759 0.1979 0.0149)',
      '13': 'color(srgb 0.2892 0.1651 0.0564)',
      '14': 'color(srgb 0.9799 0.8401 0.7357)',
      '15': 'color(srgb 1.0486 0.9881 0.9439)',
    },
    red: {
      '1': 'color(srgb 1.0733 0.9374 0.9308)',
      '2': 'color(srgb 1.0597 0.8688 0.8604)',
      '3': 'color(srgb 1.0542 0.8145 0.8051)',
      '4': 'color(srgb 1.0515 0.738 0.7283)',
      '5': 'color(srgb 1.051 0.6351 0.6286)',
      '6': 'color(srgb 1.047 0.5242 0.5279)',
      '7': 'color(srgb 1.0319 0.4066 0.4305)',
      '8': 'color(srgb 0.9464 0.1561 0.2668)',
      '9': 'color(srgb 0.778 -0.0449 0.1747)',
      '10': 'color(srgb 0.6712 0.0142 0.1555)',
      '11': 'color(srgb 0.5582 0.0812 0.1448)',
      '12': 'color(srgb 0.4461 0.1079 0.1346)',
      '13': 'color(srgb 0.3407 0.111 0.1202)',
      '14': 'color(srgb 1.0531 0.7959 0.7862)',
      '15': 'color(srgb 1.0832 0.9702 0.9646)',
    },
  },
  neutral: {
    '1': 'color(srgb 0.0967 0.1 0.1028)',
    '2': 'color(srgb 0.1062 0.1101 0.1133)',
    '3': 'color(srgb 0.3218 0.3619 0.395)',
    '4': 'color(srgb 0.1715 0.1808 0.1886)',
    '5': 'color(srgb 0.3043 0.3395 0.3685)',
    '6': 'color(srgb 0.4351 0.5073 0.5666)',
    '7': 'color(srgb 0.4498 0.5252 0.5871)',
    '8': 'color(srgb 0.6227 0.7067 0.7758)',
    '9': 'color(srgb 0.7056 0.7801 0.8417)',
    '10': 'color(srgb 0.7938 0.8541 0.9041)',
    '11': 'color(srgb 0.8692 0.9164 0.9557)',
    '12': 'color(srgb 0.9147 0.9542 0.9871)',
    '13': 'color(srgb 0.96 0.9923 1.0194)',
    '14': 'color(srgb 0.1983 0.211 0.2216)',
    '15': 'color(srgb 0.0127 0.013 0.0132)',
  },
  overlay: {
    scrim: '#1d1d1d1a',
  },
  primitives: {
    fontFamily: {
      equinor: 'Equinor',
      inter: 'Inter',
    },
    lineheightScale: {
      '100': {
        default: '12px',
      },
      '200': {
        default: '16px',
      },
      '300': {
        default: '16px',
      },
      '400': {
        default: '20px',
      },
      '500': {
        default: '24px',
      },
      '600': {
        default: '24px',
      },
      '700': {
        default: '28px',
      },
      '800': {
        default: '32px',
      },
      '900': {
        default: '32px',
      },
      '1000': {
        default: '36px',
      },
      '1100': {
        default: '40px',
      },
    },
    spacing: {
      '0': '0px',
      '6': '1px',
      '12': '2px',
      '19': '3px',
      '25': '4px',
      '37': '6px',
      '50': '8px',
      '62': '10px',
      '75': '12px',
      '87': '14px',
      '100': '16px',
      '125': '20px',
      '150': '24px',
      '175': '28px',
      '200': '32px',
      '225': '36px',
      '250': '40px',
      '275': '44px',
      '300': '48px',
      '325': '52px',
      '350': '56px',
      '375': '60px',
      '400': '64px',
      '450': '72px',
      '500': '80px',
      '550': '88px',
      '600': '96px',
      '700': '112px',
      '800': '128px',
      '900': '144px',
      '1000': '160px',
      '1100': '176px',
      '1200': '192px',
      '1300': '208px',
      '1400': '224px',
      '1500': '240px',
      '1600': '256px',
      '1700': '272px',
      '1800': '288px',
      '1900': '304px',
      '2000': '320px',
      '2100': '336px',
      '2200': '352px',
    },
    typeScale: {
      equinor: {
        '100': {
          fontSize: '10px',
        },
        '200': {
          fontSize: '12px',
        },
        '300': {
          fontSize: '14px',
        },
        '400': {
          fontSize: '16px',
        },
        '500': {
          fontSize: '18px',
        },
        '600': {
          fontSize: '21px',
        },
        '700': {
          fontSize: '24px',
        },
        '800': {
          fontSize: '28px',
        },
        '900': {
          fontSize: '32px',
        },
        '1000': {
          fontSize: '36px',
        },
        '1100': {
          fontSize: '42px',
        },
      },
      inter: {
        '100': {
          fontSize: '9px',
        },
        '200': {
          fontSize: '10px',
        },
        '300': {
          fontSize: '12px',
        },
        '400': {
          fontSize: '14px',
        },
        '500': {
          fontSize: '16px',
        },
        '600': {
          fontSize: '18px',
        },
        '700': {
          fontSize: '21px',
        },
        '800': {
          fontSize: '24px',
        },
        '900': {
          fontSize: '28px',
        },
        '1000': {
          fontSize: '32px',
        },
        '1100': {
          fontSize: '37px',
        },
      },
      trackingNormal: '0',
    },
    weightScale: {
      bolder: '500',
      lighter: '300',
      normal: '400',
    },
  },
  shadow: {
    high: {
      ambient: {
        /** Figma Elevation/Shadow/High/Ambient/blur */
        blur: '16px',
        /** Figma Elevation/Shadow/High/Ambient/color */
        color: 'color(srgb 0 0 0 / 0.12)',
        /** Figma Elevation/Shadow/High/Ambient/spread */
        spread: '6px',
        /** Figma Elevation/Shadow/High/Ambient/offset-x */
        x: '0px',
        /** Figma Elevation/Shadow/High/Ambient/offset-y */
        y: '12px',
      },
      key: {
        /** Figma Elevation/Shadow/High/Key/blur */
        blur: '12px',
        /** Figma Elevation/Shadow/High/Key/color */
        color: 'color(srgb 0 0 0 / 0.2)',
        /** Figma Elevation/Shadow/High/Key/spread */
        spread: '0px',
        /** Figma Elevation/Shadow/High/Key/offset-x */
        x: '0px',
        /** Figma Elevation/Shadow/High/Key/offset-y */
        y: '4px',
      },
    },
    low: {
      ambient: {
        /** Figma Elevation/Shadow/Low/Ambient/blur */
        blur: '8px',
        /** Figma Elevation/Shadow/Low/Ambient/color */
        color: 'color(srgb 0 0 0 / 0.12)',
        /** Figma Elevation/Shadow/Low/Ambient/spread */
        spread: '3px',
        /** Figma Elevation/Shadow/Low/Ambient/offset-x */
        x: '0px',
        /** Figma Elevation/Shadow/Low/Ambient/offset-y */
        y: '4px',
      },
      key: {
        /** Figma Elevation/Shadow/Low/Key/blur */
        blur: '8px',
        /** Figma Elevation/Shadow/Low/Key/color */
        color: 'color(srgb 0 0 0 / 0.2)',
        /** Figma Elevation/Shadow/Low/Key/spread */
        spread: '0px',
        /** Figma Elevation/Shadow/Low/Key/offset-x */
        x: '0px',
        /** Figma Elevation/Shadow/Low/Key/offset-y */
        y: '1px',
      },
    },
  },
  spacing: {
    '2xl': '28px',
    '2xs': '6px',
    '3xl': '32px',
    '3xs': '4px',
    '4xs': '2px',
    lg: '20px',
    md: '16px',
    none: '0px',
    sm: '12px',
    xl: '24px',
    xs: '8px',
  },
  success: {
    '1': 'color(srgb 0.0907 0.104 0.0895)',
    '2': 'color(srgb 0.0993 0.1146 0.0979)',
    '3': 'color(srgb 0.2357 0.4039 0.2266)',
    '4': 'color(srgb 0.1542 0.1915 0.1512)',
    '5': 'color(srgb 0.2305 0.3767 0.222)',
    '6': 'color(srgb 0.2591 0.5793 0.2493)',
    '7': 'color(srgb 0.2647 0.6002 0.2548)',
    '8': 'color(srgb 0.4333 0.7928 0.4173)',
    '9': 'color(srgb 0.5491 0.859 0.5312)',
    '10': 'color(srgb 0.6749 0.9204 0.6577)',
    '11': 'color(srgb 0.78 0.9699 0.7652)',
    '12': 'color(srgb 0.8415 0.9997 0.8284)',
    '13': 'color(srgb 0.901 1.0302 0.89)',
    '14': 'color(srgb 0.1742 0.2255 0.1702)',
    '15': 'color(srgb 0.0122 0.0133 0.012)',
  },
  text: {
    interactive: {
      disabled: 'color(srgb 0.4498 0.5252 0.5871)',
      link: {
        default: 'color(srgb 0.3547 0.7329 0.9853)',
        hover: 'color(srgb 0.4883 0.8064 1.0297)',
        pressed: 'color(srgb 0.6301 0.878 1.0586)',
      },
    },
    inverted: 'color(srgb 0.0967 0.1 0.1028)',
    onDefault: {
      accent: 'color(srgb 0.6748 0.8901 0.9136)',
      danger: 'color(srgb 1.19 0.6735 0.6697)',
      info: 'color(srgb 0.6301 0.878 1.0586)',
      neutral: 'color(srgb 0.7938 0.8541 0.9041)',
      success: 'color(srgb 0.6749 0.9204 0.6577)',
      warning: 'color(srgb 1.0592 0.7758 0.5542)',
    },
    onEmphasis: {
      accent: 'color(srgb 0.0122 0.0132 0.0133)',
      danger: 'color(srgb 0.015 0.0122 0.0121)',
      info: 'color(srgb 0.012 0.0131 0.0141)',
      neutral: 'color(srgb 0.0127 0.013 0.0132)',
      success: 'color(srgb 0.0122 0.0133 0.012)',
      warning: 'color(srgb 0.0141 0.0126 0.0116)',
    },
    onMuted: {
      /** Text/icon on muted status background. */
      accent: 'color(srgb 0.8415 0.9786 0.9934)',
      /** Text/icon on muted status background. */
      danger: 'color(srgb 1.1892 0.8456 0.8346)',
      /** Text/icon on muted status background. */
      info: 'color(srgb 0.8143 0.972 1.0904)',
      /** Text/icon on muted status background. */
      neutral: 'color(srgb 0.9147 0.9542 0.9871)',
      /** Text/icon on muted status background. */
      success: 'color(srgb 0.8415 0.9997 0.8284)',
      /** Text/icon on muted status background. */
      warning: 'color(srgb 1.094 0.9064 0.7654)',
    },
    primary: 'color(srgb 0.96 0.9923 1.0194)',
    secondary: 'color(srgb 0.6227 0.7067 0.7758)',
    tertiary: 'color(srgb 0.4498 0.5252 0.5871)',
  },
  typography: {
    header: {
      '2xl': {
        fontSize: '24px',
        lineHeight: '28px',
      },
      '3xl': {
        fontSize: '28px',
        lineHeight: '32px',
      },
      '4xl': {
        fontSize: '32px',
        lineHeight: '36px',
      },
      lg: {
        fontSize: '18px',
        lineHeight: '24px',
      },
      md: {
        fontSize: '16px',
        lineHeight: '20px',
      },
      sm: {
        fontSize: '14px',
        lineHeight: '16px',
      },
      xl: {
        fontSize: '21px',
        lineHeight: '24px',
      },
      xs: {
        fontSize: '12px',
        lineHeight: '16px',
      },
    },
    ui: {
      '2xl': {
        fontSize: '21px',
        lineHeight: '28px',
      },
      '3xl': {
        fontSize: '24px',
        lineHeight: '32px',
      },
      '4xl': {
        fontSize: '28px',
        lineHeight: '32px',
      },
      '5xl': {
        fontSize: '32px',
        lineHeight: '36px',
      },
      lg: {
        fontSize: '16px',
        lineHeight: '24px',
      },
      md: {
        fontSize: '14px',
        lineHeight: '20px',
      },
      sm: {
        fontSize: '12px',
        lineHeight: '16px',
      },
      xl: {
        fontSize: '18px',
        lineHeight: '24px',
      },
      xs: {
        fontSize: '10px',
        lineHeight: '16px',
      },
    },
  },
  warning: {
    '1': 'color(srgb 0.1122 0.0962 0.0844)',
    '2': 'color(srgb 0.124 0.1056 0.0919)',
    '3': 'color(srgb 0.4932 0.3055 0.1461)',
    '4': 'color(srgb 0.2137 0.1696 0.1363)',
    '5': 'color(srgb 0.4555 0.291 0.1549)',
    '6': 'color(srgb 0.7353 0.3963 -0.0285)',
    '7': 'color(srgb 0.7629 0.4089 -0.0544)',
    '8': 'color(srgb 0.9771 0.5841 0.2228)',
    '9': 'color(srgb 1.0261 0.6773 0.3888)',
    '10': 'color(srgb 1.0592 0.7758 0.5542)',
    '11': 'color(srgb 1.081 0.8579 0.6882)',
    '12': 'color(srgb 1.094 0.9064 0.7654)',
    '13': 'color(srgb 1.1083 0.9541 0.8391)',
    '14': 'color(srgb 0.2555 0.1952 0.1494)',
    '15': 'color(srgb 0.0141 0.0126 0.0116)',
  },
  weight: {
    bolder: '500',
    lighter: '300',
    normal: '400',
  },
} as const;

export type Theme = typeof theme;
