export const disabled = {
  outlined: {
    height: '36px',
    background: 'transparent',
    border: {
      color: 'rgba(220, 220, 220, 1)',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  ghost: {
    height: '36px',
    background: 'transparent',
    border: {
      color: 'transparent',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  ghost_icon: {
    height: '24px',
    width: '24px',
    color: 'rgba(190, 190, 190, 1)',
    background: 'transparent',
    border: {
      color: 'transparent',
      width: 0,
      radius: '',
    },
    clickbound: '48px',
    clickboundOffset: '12px',
  },
  contained_right_icon: {
    height: '36px',
    background: 'rgba(234, 234, 234, 1)',
    border: {
      color: 'transparent',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
      right_icon: '8px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  outlined_right_icon: {
    height: '36px',
    background: 'transparent',
    border: {
      color: 'rgba(220, 220, 220, 1)',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
      right_icon: '8px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  ghost_right_icon: {
    height: '36px',
    background: 'transparent',
    border: {
      color: 'transparent',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
      right_icon: '8px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  contained_left_icon: {
    height: '36px',
    background: 'rgba(234, 234, 234, 1)',
    border: {
      color: 'transparent',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
      left_icon: '8px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  outlined_left_icon: {
    height: '36px',
    background: 'transparent',
    border: {
      color: 'rgba(220, 220, 220, 1)',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
      left_icon: '8px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  ghost_left_icon: {
    height: '36px',
    background: 'transparent',
    border: {
      color: 'transparent',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
      left_icon: '8px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
  contained: {
    height: '36px',
    background: 'rgba(234, 234, 234, 1)',
    border: {
      color: 'transparent',
      width: '1px',
      radius: '4px',
    },
    color: 'rgba(190, 190, 190, 1)',
    typography: {
      color: 'rgba(190, 190, 190, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'center',
    },
    spacing: {
      left: '16px',
      right: '16px',
    },
    clickbound: '48px',
    clickboundOffset: '6px',
  },
}
