/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const font = {
  family: {
    header: 'Equinor',
    ui: 'Inter',
  },
  weight: {
    bold: 700,
    medium: 500,
    normal: 400,
  },
} as const

export type Font = typeof font
