# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: eds-cdn-demo-$(Build.BuildId)

trigger:
  batch: "true"
  branches:
    include:
    - feature/demo-cdn
  paths:
    include:
    - apps/demo-cdn

pr:
  branches:
    include:
    - develop
    - feature/demo-cdn
  paths:
    include:
    - apps/demo-cdn

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: eds-build-tokens
- name: IMAGE_NAME
  value: eds-cdn-demo:$(Build.BuildId)-$(Build.SourceBranchName)
- name: ROOT_FOLDER
  value: /apps/demo-cdn

steps:
- script: docker build -f .$(ROOT_FOLDER)/Dockerfile -t $(IMAGE_NAME) .$(ROOT_FOLDER)
  displayName: 'Docker build'

- task: Docker@1
  displayName: 'Tag an image'
  inputs:
    azureSubscriptionEndpoint: 'eds-rg-dev'
    azureContainerRegistry: edscontainers.azurecr.io
    imageName: '$(IMAGE_NAME)'
    includeLatestTag: true
    command: Tag image

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'eds-rg-dev'
    azureContainerRegistry: edscontainers.azurecr.io
    command: Push an image
    imageName: '$(IMAGE_NAME)'
