import figma from '@figma/code-connect'

/**
 * Auto-generated Code Connect entries for icons.
 * Generated by scripts/generate-icon-figma-connect.mjs
 *
 * Each icon is connected to return its name as a string,
 * which can be used with figma.instance<string>() in parent components.
 */

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23677',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_forward_ios',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23676',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_back_ios',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23669',
  {
    variant: { Density: 'Default' },
    example: () => 'chevron_left',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23673',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23685',
  {
    variant: { Density: 'Default' },
    example: () => 'accessible',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23675',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23697',
  {
    variant: { Density: 'Default' },
    example: () => 'close',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23678',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_drop_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23679',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_drop_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23680',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_drop_right',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23698',
  {
    variant: { Density: 'Default' },
    example: () => 'search',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23699',
  {
    variant: { Density: 'Default' },
    example: () => 'checkbox',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A7737',
  {
    variant: { Density: 'Default' },
    example: () => 'chevron_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23681',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_drop_left',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23691',
  {
    variant: { Density: 'Default' },
    example: () => 'error_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23696',
  {
    variant: { Density: 'Default' },
    example: () => 'check_circle_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23688',
  {
    variant: { Density: 'Default' },
    example: () => 'notifications',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23689',
  {
    variant: { Density: 'Default' },
    example: () => 'notifications_active',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23670',
  {
    variant: { Density: 'Default' },
    example: () => 'chevron_right',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23686',
  {
    variant: { Density: 'Default' },
    example: () => 'thumbs_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23693',
  {
    variant: { Density: 'Default' },
    example: () => 'calendar',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23692',
  {
    variant: { Density: 'Default' },
    example: () => 'warning_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23674',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_forward',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23687',
  {
    variant: { Density: 'Default' },
    example: () => 'placeholder_icon',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23671',
  {
    variant: { Density: 'Default' },
    example: () => 'chevron_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23700',
  {
    variant: { Density: 'Default' },
    example: () => 'checkbox_outline',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23701',
  {
    variant: { Density: 'Default' },
    example: () => 'checkbox_indeterminate',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23694',
  {
    variant: { Density: 'Default' },
    example: () => 'time',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23672',
  {
    variant: { Density: 'Default' },
    example: () => 'arrow_back',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23702',
  {
    variant: { Density: 'Default' },
    example: () => 'fullscreen',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23683',
  {
    variant: { Density: 'Default' },
    example: () => 'subdirectory_arrow_right',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23690',
  {
    variant: { Density: 'Default' },
    example: () => 'notifications_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7153%3A23682',
  {
    variant: { Density: 'Default' },
    example: () => 'subdirectory_arrow_left',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A537',
  {
    example: () => 'power_button_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=108%3A94',
  {
    example: () => 'res_hd_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1522',
  {
    example: () => 'file',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2471',
  {
    example: () => 'collection_3',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2759',
  {
    example: () => 'assignment_returned',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6725',
  {
    example: () => 'toilet',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2785',
  {
    example: () => 'bookmark_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5034',
  {
    example: () => 'inbox',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A270',
  {
    example: () => 'near_me',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7458',
  {
    example: () => 'substation_offshore',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4455',
  {
    example: () => 'stop',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2412',
  {
    example: () => 'ticket',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A27',
  {
    example: () => 'zoom_out',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9631%3A7642',
  {
    example: () => 'stop_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3189%3A1',
  {
    example: () => 'gas',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6294',
  {
    example: () => 'apps',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4575',
  {
    example: () => 'call_end',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6055',
  {
    example: () => 'device_unknown',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2465',
  {
    example: () => 'collection_2',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6005',
  {
    example: () => 'wrap_text',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2477',
  {
    example: () => 'place_unknown',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A3873',
  {
    example: () => 'touch',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2548',
  {
    example: () => 'terrain',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2233',
  {
    example: () => 'toll',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8671%3A7559',
  {
    example: () => 'slack',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9013%3A7658',
  {
    example: () => 'reduce',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2120',
  {
    example: () => 'place_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1991',
  {
    example: () => 'texture',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5746',
  {
    example: () => 'format_color_text',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1078',
  {
    example: () => 'folder_shared',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4398',
  {
    example: () => 'replay_5',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3407',
  {
    example: () => 'unfold_less',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4879',
  {
    example: () => 'share_screen_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4704',
  {
    example: () => 'email',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4286',
  {
    example: () => 'new_alert',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5726',
  {
    example: () => 'format_bold',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=5839%3A7141',
  {
    example: () => 'inspect_rotation',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2009',
  {
    example: () => 'label_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4267',
  {
    example: () => 'mic_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6246',
  {
    example: () => 'speaker_group',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6184',
  {
    example: () => 'iphone',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2357',
  {
    example: () => 'laundry',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A757',
  {
    example: () => 'spotify',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2048',
  {
    example: () => 'print_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2206',
  {
    example: () => 'subway',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4550',
  {
    example: () => 'text_rotation_angled_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4540',
  {
    example: () => 'text_rotation_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2559',
  {
    example: () => 'train',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A949',
  {
    example: () => 'alarm',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A758',
  {
    example: () => 'youtube',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2648',
  {
    example: () => 'bluetooth_searching',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2340',
  {
    example: () => 'grocery_store',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4145',
  {
    example: () => 'fast_rewind',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1687',
  {
    example: () => 'record_voice',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A0',
  {
    example: () => 'cocktail',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6206',
  {
    example: () => 'router',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2252',
  {
    example: () => 'flight',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6118',
  {
    example: () => 'keyboard_capslock',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A927',
  {
    example: () => 'battery_alert',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2483',
  {
    example: () => 'collection_5',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2753',
  {
    example: () => 'assignment_return',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1427',
  {
    example: () => 'maximize',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1695',
  {
    example: () => 'record_voice_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2510',
  {
    example: () => 'collection_9',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1122',
  {
    example: () => 'van',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2489',
  {
    example: () => 'collection_6',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2477',
  {
    example: () => 'collection_4',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1967',
  {
    example: () => 'style',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2346',
  {
    example: () => 'hospital',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2522',
  {
    example: () => 'satellite',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2392',
  {
    example: () => 'parking',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6179',
  {
    example: () => 'android',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1096',
  {
    example: () => 'music_note',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6829',
  {
    example: () => 'meeting_room_off_',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5610',
  {
    example: () => 'border_outer',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2829',
  {
    example: () => 'flip',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A553',
  {
    example: () => 'motorcycle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=108%3A121',
  {
    example: () => 'closed_caption_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6012',
  {
    example: () => 'google_cast',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2643',
  {
    example: () => 'bluetooth_disabled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4258',
  {
    example: () => 'mic',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4193',
  {
    example: () => 'forward_10',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6824',
  {
    example: () => 'meeting_room',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2568',
  {
    example: () => 'tram',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1100',
  {
    example: () => 'music_note_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2304',
  {
    example: () => 'convenience_store',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2296',
  {
    example: () => 'translate',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4199',
  {
    example: () => 'forward_30',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5705',
  {
    example: () => 'format_align_justify',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2442',
  {
    example: () => 'taxi',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2188',
  {
    example: () => 'car',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9011%3A7652',
  {
    example: () => 'sheet_left_position',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4555',
  {
    example: () => 'text_rotation_angled_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4962',
  {
    example: () => 'clear',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2540',
  {
    example: () => 'subway_tunnel',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5619',
  {
    example: () => 'border_right',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A753',
  {
    example: () => 'microsoft_excel',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A192',
  {
    example: () => 'commute',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1335',
  {
    example: () => 'grid_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2955',
  {
    example: () => 'done_all',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3399',
  {
    example: () => 'first_page',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6834',
  {
    example: () => 'pool',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1257',
  {
    example: () => 'lock_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3395',
  {
    example: () => 'last_page',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5049',
  {
    example: () => 'priority_low',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2195',
  {
    example: () => 'railway',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A108',
  {
    example: () => 'flight_takeoff',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7256',
  {
    example: () => 'instrument',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3095',
  {
    example: () => 'eject',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6173',
  {
    example: () => 'mouse',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A31',
  {
    example: () => 'restaurant',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A761',
  {
    example: () => 'chrome',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4488',
  {
    example: () => 'video_call',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A766',
  {
    example: () => 'apple_app_store',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4560',
  {
    example: () => 'text_rotation_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2294',
  {
    example: () => 'car_wash',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A247',
  {
    example: () => 'gps_fixed',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6122',
  {
    example: () => 'keyboard_hide',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5973',
  {
    example: () => 'keyboard_space_bar',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2796',
  {
    example: () => 'rotate_90_degrees_ccw',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4402',
  {
    example: () => 'replay_10',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6795',
  {
    example: () => 'gym',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6286',
  {
    example: () => 'smartwatch',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A104',
  {
    example: () => 'flight_land',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4189',
  {
    example: () => 'forward_5',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5018',
  {
    example: () => 'gesture',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2491',
  {
    example: () => 'place_person',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4262',
  {
    example: () => 'mic_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4517',
  {
    example: () => 'volume_mute',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A762',
  {
    example: () => 'facebook',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5769',
  {
    example: () => 'format_line_spacing',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2496',
  {
    example: () => 'collection_7',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A11',
  {
    example: () => 'drink',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1332',
  {
    example: () => 'dropper',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2801',
  {
    example: () => 'rotate_left',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4634',
  {
    example: () => 'contact_email',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1974',
  {
    example: () => 'fingerprint_scanner',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6913',
  {
    example: () => 'city',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4677',
  {
    example: () => 'dialpad',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5751',
  {
    example: () => 'format_indent_decrease',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A768',
  {
    example: () => 'microsoft_edge',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6239',
  {
    example: () => 'speaker',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6215',
  {
    example: () => 'scanner',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6144',
  {
    example: () => 'keyboard_voice',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A85',
  {
    example: () => 'phone',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=73%3A182',
  {
    example: () => 'opacity',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A752',
  {
    example: () => 'facebook_messenger',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2845',
  {
    example: () => 'crop_rotate',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2254',
  {
    example: () => 'hotel',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1890',
  {
    example: () => 'explore_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2180',
  {
    example: () => 'bus',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2233',
  {
    example: () => 'place_edit',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5759',
  {
    example: () => 'format_indent_increase',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1568',
  {
    example: () => 'library_music',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A283',
  {
    example: () => 'compass_calibration',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4503',
  {
    example: () => 'videocam',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2150',
  {
    example: () => 'departure_board',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A274',
  {
    example: () => 'navigation',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5819',
  {
    example: () => 'format_size',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A759',
  {
    example: () => 'youtube_alt',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4393',
  {
    example: () => 'repeat_one',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6771',
  {
    example: () => 'dice',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2055',
  {
    example: () => 'print',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1769',
  {
    example: () => 'shopping_basket',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6068',
  {
    example: () => 'dock',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1760',
  {
    example: () => 'shopping_cart_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1207',
  {
    example: () => 'view_module',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4441',
  {
    example: () => 'snooze',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6757',
  {
    example: () => 'beach',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6631',
  {
    example: () => 'high_priority_',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A970',
  {
    example: () => 'alarm_on',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4310',
  {
    example: () => 'pause_circle_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1462',
  {
    example: () => 'key',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A252',
  {
    example: () => 'gps_not_fixed',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5927',
  {
    example: () => 'multiline_chart',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A533',
  {
    example: () => 'power_button',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1547',
  {
    example: () => 'spellcheck',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1428',
  {
    example: () => 'do_not_disturb',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4222',
  {
    example: () => 'hearing',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A256',
  {
    example: () => 'gps_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4089',
  {
    example: () => 'apple_airplay',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4895',
  {
    example: () => 'unsubscribe',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5735',
  {
    example: () => 'format_color_fill',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A5',
  {
    example: () => 'coffee',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5741',
  {
    example: () => 'format_color_reset',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4178',
  {
    example: () => 'pin',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3743',
  {
    example: () => 'bandage',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2581',
  {
    example: () => 'transit_enter_exit',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A85',
  {
    example: () => 'all_out',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2851',
  {
    example: () => 'crop',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5767',
  {
    example: () => 'format_italics',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5557',
  {
    example: () => 'border_horizontal',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4507',
  {
    example: () => 'videocam_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2239',
  {
    example: () => 'ev_station',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A760',
  {
    example: () => 'ios_logo',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A763',
  {
    example: () => 'instagram',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4272',
  {
    example: () => 'missed_video_call',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1216',
  {
    example: () => 'view_quilt',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9835%3A7686',
  {
    example: () => 'sheet_top_position',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A751',
  {
    example: () => 'whats_app',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3184%3A10',
  {
    example: () => 'circuit',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4546',
  {
    example: () => 'call_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6073',
  {
    example: () => 'gamepad',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5838',
  {
    example: () => 'format_underline',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4556',
  {
    example: () => 'business',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2631',
  {
    example: () => 'bluetooth',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7917%3A7386',
  {
    example: () => 'subsea_drone',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A524',
  {
    example: () => 'light',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1070',
  {
    example: () => 'calendar_reject',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A765',
  {
    example: () => 'twitter',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2455',
  {
    example: () => 'money',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2081',
  {
    example: () => 'power',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=81%3A3085',
  {
    example: () => 'donut_large',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4989',
  {
    example: () => 'email_draft',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4845',
  {
    example: () => 'share_screen',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5698',
  {
    example: () => 'format_align_center',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4565',
  {
    example: () => 'text_rotation_none',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5975',
  {
    example: () => 'format_strikethrough',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1526',
  {
    example: () => 'folder_favorite',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2377',
  {
    example: () => 'cinema',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5996',
  {
    example: () => 'vertical_align_center',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2517',
  {
    example: () => 'collection_9_plus',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3175%3A7191',
  {
    example: () => 'bearing',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7174',
  {
    example: () => 'ducting',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7345',
  {
    example: () => 'telecom',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6891%3A7457',
  {
    example: () => 'miniplayer',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2160',
  {
    example: () => 'directions',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4512',
  {
    example: () => 'volume_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A764',
  {
    example: () => 'apple_logo',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5576',
  {
    example: () => 'border_inner',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5509',
  {
    example: () => 'border_bottom',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1802',
  {
    example: () => 'nature_people',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4653',
  {
    example: () => 'contacts',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2636',
  {
    example: () => 'bluetooth_connected',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5591',
  {
    example: () => 'border_left',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6225',
  {
    example: () => 'sim_card',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2575',
  {
    example: () => 'transfer',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3175%3A7192',
  {
    example: () => 'pressure',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4077',
  {
    example: () => 'res_4k_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=108%3A119',
  {
    example: () => 'res_4k_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4215',
  {
    example: () => 'res_hd_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2215',
  {
    example: () => 'transit',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6891%3A7478',
  {
    example: () => 'miniplayer_fullscreen',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1781',
  {
    example: () => 'shopping_cart_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2502',
  {
    example: () => 'collection_8',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1056',
  {
    example: () => 'folder_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5712',
  {
    example: () => 'format_align_left',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6797',
  {
    example: () => 'cafe',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1475',
  {
    example: () => 'mail_unread',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3636',
  {
    example: () => 'swap_vertical_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1192',
  {
    example: () => 'view_day',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6083',
  {
    example: () => 'headset',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6167',
  {
    example: () => 'memory',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3282',
  {
    example: () => 'flash_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5667',
  {
    example: () => 'border_vertical',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2910',
  {
    example: () => 'attachment',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2265',
  {
    example: () => 'layers_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A349',
  {
    example: () => 'pregnant_woman',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5719',
  {
    example: () => 'format_align_right',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5648',
  {
    example: () => 'border_top',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6860',
  {
    example: () => 'smoking',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A770',
  {
    example: () => 'google_play',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2172',
  {
    example: () => 'restore_page',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A572',
  {
    example: () => 'flame',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6817',
  {
    example: () => 'fridge',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5731',
  {
    example: () => 'format_clear',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6714',
  {
    example: () => 'video_chat',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A360',
  {
    example: () => 'wheelchair',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2396',
  {
    example: () => 'pharmacy',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9011%3A7649',
  {
    example: () => 'sheet_bottom_position',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2629',
  {
    example: () => 'usb',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1160',
  {
    example: () => 'vertical_split',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A35',
  {
    example: () => 'dining',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A940',
  {
    example: () => 'battery_unknown',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7249',
  {
    example: () => 'electrical',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2371',
  {
    example: () => 'mall',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4521',
  {
    example: () => 'volume_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6852',
  {
    example: () => 'smoking_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A750',
  {
    example: () => 'skype',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9011%3A7646',
  {
    example: () => 'open_side_sheet',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3623',
  {
    example: () => 'swap_horizontal',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=73%3A109',
  {
    example: () => 'external_link',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5842',
  {
    example: () => 'functions',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3633',
  {
    example: () => 'swap_vertical',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=432%3A6795',
  {
    example: () => 'switch_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2136',
  {
    example: () => 'category',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6001',
  {
    example: () => 'vertical_align_top',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4981',
  {
    example: () => 'delete_multiple',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5044',
  {
    example: () => 'link_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1174',
  {
    example: () => 'view_array',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5783',
  {
    example: () => 'format_list_numbered',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5803',
  {
    example: () => 'format_quote',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=12170%3A6777',
  {
    example: () => 'monopile',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9651%3A7688',
  {
    example: () => 'stop_circle_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7160',
  {
    example: () => 'grid_layer',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7185',
  {
    example: () => 'hill_shading',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4828',
  {
    example: () => 'details',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3016',
  {
    example: () => 'sort_by_alpha',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4545',
  {
    example: () => 'text_rotation_vertical',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2892',
  {
    example: () => 'rotate_right',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2759',
  {
    example: () => 'update',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2787',
  {
    example: () => 'bookmark_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4012',
  {
    example: () => 'work',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6661',
  {
    example: () => 'comment_important',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1611',
  {
    example: () => 'restore_from_trash',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3141',
  {
    example: () => 'star_half',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5117',
  {
    example: () => 'report_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4050',
  {
    example: () => 'error_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4914',
  {
    example: () => 'add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5134',
  {
    example: () => 'select_all',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1180',
  {
    example: () => 'view_carousel_',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1413',
  {
    example: () => 'blocked',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A24',
  {
    example: () => 'fast_food',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7128',
  {
    example: () => 'fault',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4301',
  {
    example: () => 'pause',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2165',
  {
    example: () => 'bike',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6876',
  {
    example: () => 'cake',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6654',
  {
    example: () => 'comment_more',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4410',
  {
    example: () => 'replay_30',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5986',
  {
    example: () => 'text_field',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6764',
  {
    example: () => 'briefcase',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9845%3A7678',
  {
    example: () => 'sheet_right_position',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1064',
  {
    example: () => 'calendar_accept',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A3878',
  {
    example: () => 'track_changes',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2552',
  {
    example: () => 'traffic_light',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1141',
  {
    example: () => 'comment_chat_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A956',
  {
    example: () => 'alarm_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2947',
  {
    example: () => 'camera_add_photo',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2358',
  {
    example: () => 'offline',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2019',
  {
    example: () => 'timer_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A245',
  {
    example: () => 'notifications_important',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A79',
  {
    example: () => 'camera',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1548',
  {
    example: () => 'library_video',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4324',
  {
    example: () => 'play_circle_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6889%3A7360',
  {
    example: () => 'tag_main_equipment',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7918%3A7396',
  {
    example: () => 'onshore_drone',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3783%3A7022',
  {
    example: () => 'filter_alt',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6377',
  {
    example: () => 'more_vertical',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4790',
  {
    example: () => 'call',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2583',
  {
    example: () => 'trip_origin',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=73%3A145',
  {
    example: () => 'flip_to_front',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=73%3A130',
  {
    example: () => 'flip_to_back',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=5839%3A7062',
  {
    example: () => 'power_bi',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1798',
  {
    example: () => 'nature',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A8848',
  {
    example: () => 'priority_high',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2013',
  {
    example: () => 'timer',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1633',
  {
    example: () => 'help_outline',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6889%3A7376',
  {
    example: () => 'tag_special_equipment',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4644',
  {
    example: () => 'contact_phone',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5105',
  {
    example: () => 'report',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6088',
  {
    example: () => 'headset_mic',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A963',
  {
    example: () => 'alarm_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4528',
  {
    example: () => 'volume_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4957',
  {
    example: () => 'block',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2971',
  {
    example: () => 'slideshow',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3704',
  {
    example: () => 'info_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6037',
  {
    example: () => 'desktop_mac',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5094',
  {
    example: () => 'remove_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6258',
  {
    example: () => 'tablet_android',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1437',
  {
    example: () => 'toc',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6263',
  {
    example: () => 'tablet_ipad',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=329%3A93',
  {
    example: () => 'radio_button_selected',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5124',
  {
    example: () => 'save',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5452',
  {
    example: () => 'thermostat',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1628',
  {
    example: () => 'help',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7059',
  {
    example: () => 'mood_extremely_sad',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5175',
  {
    example: () => 'undo',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4346',
  {
    example: () => 'playlist_play',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2330',
  {
    example: () => 'download_done',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2224',
  {
    example: () => 'walk',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7028',
  {
    example: () => 'world',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2765',
  {
    example: () => 'assignment_turned_in',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5502',
  {
    example: () => 'border_all',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4921',
  {
    example: () => 'add_circle_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6932',
  {
    example: () => 'mood_very_sad',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1554',
  {
    example: () => 'library_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6330',
  {
    example: () => 'close_circle_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6041',
  {
    example: () => 'desktop_windows',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2746',
  {
    example: () => 'assignment_important',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4974',
  {
    example: () => 'cut',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A3053',
  {
    example: () => 'search_in_page',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5992',
  {
    example: () => 'vertical_align_bottom',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4925',
  {
    example: () => 'add_circle_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6676',
  {
    example: () => 'sync_problem',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2325',
  {
    example: () => 'upload',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A3058',
  {
    example: () => 'search_find_replace',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4254',
  {
    example: () => 'loop',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5065',
  {
    example: () => 'move_to_inbox',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5086',
  {
    example: () => 'redo_',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5169',
  {
    example: () => 'unarchive',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5101',
  {
    example: () => 'reply_all',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2840',
  {
    example: () => 'edit_text',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6787',
  {
    example: () => 'pram',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2780',
  {
    example: () => 'bookmarks',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A755',
  {
    example: () => 'microsoft_powerpoint',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5497',
  {
    example: () => 'bar_chart',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6018',
  {
    example: () => 'google_cast_connected',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3327',
  {
    example: () => 'sort',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7210',
  {
    example: () => 'manual_valve',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6671',
  {
    example: () => 'sync_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4320',
  {
    example: () => 'play_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6372',
  {
    example: () => 'more_horizontal',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2771',
  {
    example: () => 'autorenew',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5686',
  {
    example: () => 'bubble_chart',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A68',
  {
    example: () => 'rotate_3d',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2737',
  {
    example: () => 'assignment_user',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A255',
  {
    example: () => 'group_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A769',
  {
    example: () => 'microsoft_onedrive',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7198',
  {
    example: () => 'well',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2529',
  {
    example: () => 'store',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3219%3A6990',
  {
    example: () => 'cable',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A559',
  {
    example: () => 'sun',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1857',
  {
    example: () => 'receipt',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A938',
  {
    example: () => 'battery',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2967',
  {
    example: () => 'movie_file',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1168',
  {
    example: () => 'view_agenda',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1839',
  {
    example: () => 'list',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1223',
  {
    example: () => 'view_stream',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2791',
  {
    example: () => 'bookmark_collection',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2939',
  {
    example: () => 'file_description',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2729',
  {
    example: () => 'assignment',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2449',
  {
    example: () => 'map',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1369',
  {
    example: () => 'verified',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4021',
  {
    example: () => 'work_outline',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4416',
  {
    example: () => 'shuffle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7277',
  {
    example: () => 'junction_box',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9011%3A7588',
  {
    example: () => 'offline_document',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5090',
  {
    example: () => 'remove',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7611',
  {
    example: () => 'expand',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6889%3A7389',
  {
    example: () => 'tag_more',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2005',
  {
    example: () => 'label',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A771',
  {
    example: () => 'google_maps',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5694',
  {
    example: () => 'drag_handle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=432%3A6799',
  {
    example: () => 'switch_on',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4408',
  {
    example: () => 'replay',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1251',
  {
    example: () => 'lock_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1243',
  {
    example: () => 'security',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6891%3A7438',
  {
    example: () => 'log_out',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2703',
  {
    example: () => 'exit_to_app',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1580',
  {
    example: () => 'library_pdf',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1949',
  {
    example: () => 'favorite_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3771',
  {
    example: () => 'gavel',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6357',
  {
    example: () => 'fullscreen_exit',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3204',
  {
    example: () => 'wifi',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1503',
  {
    example: () => 'thumbs_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6033',
  {
    example: () => 'computer',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6275',
  {
    example: () => 'tv',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A682',
  {
    example: () => 'calendar_today',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7052',
  {
    example: () => 'mood_happy',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1324',
  {
    example: () => 'color_palette',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1346',
  {
    example: () => 'grid_on',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4969',
  {
    example: () => 'edit',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3761',
  {
    example: () => 'report_bug',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2168',
  {
    example: () => 'restore',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1247',
  {
    example: () => 'flagged_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8671%3A7600',
  {
    example: () => 'filter_alt_active',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1884',
  {
    example: () => 'explore',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4421',
  {
    example: () => 'skip_next',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4426',
  {
    example: () => 'skip_previous',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A767',
  {
    example: () => 'linkedin',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1775',
  {
    example: () => 'shopping_card',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1297',
  {
    example: () => 'lock_open',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1264',
  {
    example: () => 'hourglass_empty',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1269',
  {
    example: () => 'hourglass_full',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1658',
  {
    example: () => 'home',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7511',
  {
    example: () => 'toolbox_wheel',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A270',
  {
    example: () => 'person_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A264',
  {
    example: () => 'person',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A247',
  {
    example: () => 'group',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6667',
  {
    example: () => 'sync',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4930',
  {
    example: () => 'archive',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9240%3A7644',
  {
    example: () => 'wellbore',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7218',
  {
    example: () => 'surface_layer',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2321',
  {
    example: () => 'flower',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1672',
  {
    example: () => 'pan_tool',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2917',
  {
    example: () => 'attach_file',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=5839%3A7123',
  {
    example: () => 'invert',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2014',
  {
    example: () => 'tag',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4964',
  {
    example: () => 'copy',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5004',
  {
    example: () => 'flag',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3175%3A7193',
  {
    example: () => 'platform',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A211',
  {
    example: () => 'users_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5081',
  {
    example: () => 'paste',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4823',
  {
    example: () => 'compare',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7169',
  {
    example: () => 'grid_layers',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4305',
  {
    example: () => 'pause_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2846',
  {
    example: () => 'change_history',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=14140%3A6501',
  {
    example: () => 'circle_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4169',
  {
    example: () => 'record',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3752',
  {
    example: () => 'brush',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5039',
  {
    example: () => 'link',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2202',
  {
    example: () => 'run',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2334',
  {
    example: () => 'cloud_upload',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=329%3A98',
  {
    example: () => 'radio_button_unselected',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1074',
  {
    example: () => 'folder_open',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4609',
  {
    example: () => 'comment_chat',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5990',
  {
    example: () => 'title',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A932',
  {
    example: () => 'battery_charging',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2253',
  {
    example: () => 'trending_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2257',
  {
    example: () => 'trending_up',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2923',
  {
    example: () => 'delete_to_trash',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A269',
  {
    example: () => 'comment_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4618',
  {
    example: () => 'comment',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5154',
  {
    example: () => 'send',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2354',
  {
    example: () => 'cloud',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2339',
  {
    example: () => 'cloud_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2349',
  {
    example: () => 'cloud_done',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4916',
  {
    example: () => 'add_box',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2459',
  {
    example: () => 'collection_1',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3142',
  {
    example: () => 'star_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4334',
  {
    example: () => 'playlist_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2320',
  {
    example: () => 'download',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1429',
  {
    example: () => 'minimize',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2363',
  {
    example: () => 'offline_saved',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1431',
  {
    example: () => 'reorder',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3332',
  {
    example: () => 'filter_list',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1391',
  {
    example: () => 'flagged',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8047%3A7491',
  {
    example: () => 'signature',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1479',
  {
    example: () => 'language',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1560',
  {
    example: () => 'library_books',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1574',
  {
    example: () => 'library_image',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3403',
  {
    example: () => 'unfold_more',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7239',
  {
    example: () => 'heat_trace',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=77%3A18',
  {
    example: () => 'pizza',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4794',
  {
    example: () => 'focus_center',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A1070',
  {
    example: () => 'folder',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A756',
  {
    example: () => 'github',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5809',
  {
    example: () => 'format_shape',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5638',
  {
    example: () => 'border_style',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5528',
  {
    example: () => 'border_clear',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1417',
  {
    example: () => 'dashboard',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3287',
  {
    example: () => 'flash_on',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1198',
  {
    example: () => 'view_list',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8807%3A7580',
  {
    example: () => 'in_progress',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5951',
  {
    example: () => 'scatter_plot',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A589',
  {
    example: () => 'waves',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8671%3A7543',
  {
    example: () => 'expand_screen',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7450',
  {
    example: () => 'substation_onshore',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7103',
  {
    example: () => 'go_to',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A593',
  {
    example: () => 'turbine',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7039%3A7374',
  {
    example: () => 'wind_turbine',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7524',
  {
    example: () => 'toolbox_rope',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7545',
  {
    example: () => 'hand_radio',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7573',
  {
    example: () => 'craning',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7585',
  {
    example: () => 'no_craning',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7497',
  {
    example: () => 'toolbox',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=16683%3A6533',
  {
    example: () => 'drag_indicator',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=16683%3A6532',
  {
    example: () => 'drag_handle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2497',
  {
    example: () => 'pin_drop',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5466',
  {
    example: () => 'widgets',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=5839%3A7178',
  {
    example: () => 'engineering',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8517%3A7528',
  {
    example: () => 'oil',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7192',
  {
    example: () => 'formula',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1228',
  {
    example: () => 'view_week',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3308',
  {
    example: () => 'tune',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4316',
  {
    example: () => 'play',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9016%3A7664',
  {
    example: () => 'approve',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7918%3A7406',
  {
    example: () => 'aerial_drone',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A22',
  {
    example: () => 'zoom_in',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=16621%3A6514',
  {
    example: () => 'unfold_less_horizontal',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=16621%3A6515',
  {
    example: () => 'unfold_more_horizontal',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4389',
  {
    example: () => 'repeat',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2173',
  {
    example: () => 'boat',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1543',
  {
    example: () => 'file_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3153',
  {
    example: () => 'star_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=82%3A4783',
  {
    example: () => 'flare',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4116',
  {
    example: () => 'closed_caption_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=16629%3A7735',
  {
    example: () => 'experiment',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2278',
  {
    example: () => 'dollar',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1951',
  {
    example: () => 'favorite_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3033',
  {
    example: () => 'refresh',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6093',
  {
    example: () => 'keyboard',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2743',
  {
    example: () => 'settings',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5775',
  {
    example: () => 'format_list_bulleted',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2711',
  {
    example: () => 'open_in_browser',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4994',
  {
    example: () => 'file_copy',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4016',
  {
    example: () => 'work_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3209',
  {
    example: () => 'wifi_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1464',
  {
    example: () => 'visibility',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1383',
  {
    example: () => 'verified_user',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1463',
  {
    example: () => 'visibility_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3120',
  {
    example: () => 'star_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6891%3A7404',
  {
    example: () => 'thumb_pin',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2873',
  {
    example: () => 'code',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3679',
  {
    example: () => 'image_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8047%3A7437',
  {
    example: () => 'badge',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3273',
  {
    example: () => 'baby',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1930',
  {
    example: () => 'dns',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4063',
  {
    example: () => 'warning_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6335',
  {
    example: () => 'check',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2140',
  {
    example: () => 'puzzle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1915',
  {
    example: () => 'lightbulb',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3767',
  {
    example: () => 'build_wrench',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2435',
  {
    example: () => 'shipping',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2503',
  {
    example: () => 'place',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6891%3A7528',
  {
    example: () => 'tag_relations',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2928',
  {
    example: () => 'delete_forever',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A3153',
  {
    example: () => 'history',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1407',
  {
    example: () => 'blocked_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3175%3A7190',
  {
    example: () => 'gear',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8141%3A7617',
  {
    example: () => 'collapse',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A148',
  {
    example: () => 'account_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1513',
  {
    example: () => 'thumbs_up_down',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2365',
  {
    example: () => 'library',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8517%3A7538',
  {
    example: () => 'oil_barrel',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1026',
  {
    example: () => 'calendar_date_range',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A8555',
  {
    example: () => 'table_chart',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1291',
  {
    example: () => 'lock',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6140',
  {
    example: () => 'keyboard_tab',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6138',
  {
    example: () => 'keyboard_return',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6116',
  {
    example: () => 'keyboard_backspace',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2251',
  {
    example: () => 'timeline',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4709',
  {
    example: () => 'comment_discussion',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1377',
  {
    example: () => 'comment_notes',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4616',
  {
    example: () => 'comment_solid',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7911%3A7360',
  {
    example: () => 'zip_file',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2255',
  {
    example: () => 'trending_flat',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5889',
  {
    example: () => 'insert_link',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2953',
  {
    example: () => 'done',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=9013%3A7655',
  {
    example: () => 'enlarge',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A1186',
  {
    example: () => 'view_column',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8671%3A7595',
  {
    example: () => 'filter_alt_off',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=7915%3A7394',
  {
    example: () => 'anchor',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2145',
  {
    example: () => 'puzzle_filled',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A252',
  {
    example: () => 'notifications_add',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4277',
  {
    example: () => 'movie',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6885%3A7087',
  {
    example: () => 'launch',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5844',
  {
    example: () => 'format_highlight',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2773',
  {
    example: () => 'searched_history',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4340',
  {
    example: () => 'playlist_added',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2260',
  {
    example: () => 'layers',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2118',
  {
    example: () => 'view_360',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7073',
  {
    example: () => 'share',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=8671%3A7546',
  {
    example: () => 'collapse_screen',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1824',
  {
    example: () => 'credit_card',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4552',
  {
    example: () => 'email_alpha',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6367',
  {
    example: () => 'menu',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A2334',
  {
    example: () => 'gas_station',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=5839%3A7101',
  {
    example: () => 'boundaries',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=73%3A73',
  {
    example: () => 'notifications_paused',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7038',
  {
    example: () => 'mood_sad',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7033',
  {
    example: () => 'school',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7066',
  {
    example: () => 'mood_extremely_happy',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6925',
  {
    example: () => 'mood_very_happy',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A7045',
  {
    example: () => 'mood_neutral',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1595',
  {
    example: () => 'support',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3265',
  {
    example: () => 'face',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=81%3A3090',
  {
    example: () => 'donut_outlined',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=73%3A168',
  {
    example: () => 'invert_colors',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=12170%3A6779',
  {
    example: () => 'jacket',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2177',
  {
    example: () => 'setting_backup_restore',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3757',
  {
    example: () => 'measure',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=1195%3A29',
  {
    example: () => 'microsoft_outlook',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1057',
  {
    example: () => 'calendar_event',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A3627',
  {
    example: () => 'swap_horizontal_circle',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4139',
  {
    example: () => 'fast_forward',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=5839%3A7160',
  {
    example: () => 'inspect_3d',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6755',
  {
    example: () => 'infinity',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2962',
  {
    example: () => 'image',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5551',
  {
    example: () => 'border_color',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=3189%3A0',
  {
    example: () => 'beat',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A2344',
  {
    example: () => 'cloud_download',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5934',
  {
    example: () => 'pie_chart',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A4173',
  {
    example: () => 'new_label',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A365',
  {
    example: () => 'accessible_forward',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A5099',
  {
    example: () => 'reply',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=86%3A1562',
  {
    example: () => 'google_translate',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=72%3A6744',
  {
    example: () => 'snow',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=84%3A754',
  {
    example: () => 'microsoft_word',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6891%3A7439',
  {
    example: () => 'log_in',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7225',
  {
    example: () => 'pipe_support',
  },
)

figma.connect(
  'https://www.figma.com/design/BQjYMxdSdgRkdhKTDDU7L4KU?node-id=6887%3A7318',
  {
    example: () => 'line',
  },
)
