name: Visual Regression Tests

on:
  pull_request:
    paths:
      - "packages/eds-demo/**"
  push:
    branches:
      - develop
      - main
    paths:
      - "packages/eds-demo/**"

jobs:
  test:
    name: Run Visual Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/eds-demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: .

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/eds-demo/playwright-report/
          retention-days: 30

      - name: Upload test failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: packages/eds-demo/test-results/
          retention-days: 30
