name: eds-tokens-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: 'true'
  branches:
    include:
      - develop
  paths:
    include:
      - libraries/tokens

pr:
  branches:
    include:
      - develop
  paths:
    include:
      - libraries/tokens

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install -g pnpm@next
    displayName: 'Install pnpm'

  - script: pnpm --filter ./libraries/tokens install
    displayName: 'Install dependencies'

  - script: pnpm --filter ./libraries/tokens run build
    displayName: 'Run build'
