export const typography = {
  heading: {
    h1_bold: {
      color: 'var(--eds_heading__h1_bold_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '2.000rem',
      fontWeight: 700,
      lineHeight: '1.250em',
      textAlign: 'left',
    },
    h1: {
      color: 'var(--eds_heading__h1_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '2.000rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      textAlign: 'left',
    },
    h2: {
      color: 'var(--eds_heading__h2_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.750rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      textAlign: 'left',
    },
    h3: {
      color: 'var(--eds_heading__h3_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.500rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      textAlign: 'left',
    },
    h4: {
      color: 'var(--eds_heading__h4_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.250rem',
      fontWeight: 400,
      lineHeight: '1.600em',
      textAlign: 'left',
    },
    h5: {
      color: 'var(--eds_heading__h5_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.125rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.333em',
      textAlign: 'left',
    },
    h6: {
      color: 'var(--eds_heading__h6_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.500em',
      textAlign: 'left',
    },
  },
  navigation: {
    menu_title: {
      color: 'var(--eds_navigation__menu_title_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      letterSpacing: '0.013em',
      lineHeight: '1.000em',
      textAlign: 'left',
    },
    menu_tabs: {
      color: 'var(--eds_navigation__menu_tabs_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.000em',
      textAlign: 'left',
    },
    label: {
      color: 'var(--eds_navigation__label_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      lineHeight: '1.333em',
      textAlign: 'left',
    },
    drawer_active: {
      color: 'var(--eds_navigation__drawer_active_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      letterSpacing: '0.006em',
      lineHeight: '1.000em',
      textAlign: 'left',
    },
    drawer_inactive: {
      color: 'var(--eds_navigation__drawer_inactive_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.000em',
      textAlign: 'left',
    },
    button: {
      color: 'var(--eds_navigation__button_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'left',
    },
    breadcrumb: {
      color: 'var(--eds_navigation__breadcrumb_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'left',
    },
    breadcrumb_hover: {
      color: 'var(--eds_navigation__breadcrumb_hover_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textDecoration: 'underline',
      textAlign: 'left',
    },
    menu_title_hover: {
      color:
        'var(--eds_navigation__menu_title_hover_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      letterSpacing: '0.013em',
      lineHeight: '1.000em',
      textAlign: 'left',
    },
  },
  input: {
    label: {
      color: 'var(--eds_input__label_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      lineHeight: '1.333em',
      textAlign: 'left',
    },
    text: {
      color: 'var(--eds_input__text_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      letterSpacing: '0.025em',
      lineHeight: '1.500em',
      textAlign: 'left',
    },
    text_monospaced: {
      fontFeature: "'tnum' on,'lnum' on",
      color: 'var(--eds_input__text_monospaced_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      letterSpacing: '0.063em',
      lineHeight: '1.500em',
      textAlign: 'left',
    },
    helper: {
      color: 'var(--eds_input__helper_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.333em',
      textAlign: 'left',
    },
  },
  paragraph: {
    body_short_italic: {
      color:
        'var(--eds_paragraph__body_short_italic_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      fontStyle: 'italic',
      textAlign: 'left',
    },
    caption: {
      color: 'var(--eds_paragraph__caption_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'left',
    },
    meta: {
      color: 'var(--eds_paragraph__meta_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.625rem',
      fontWeight: 500,
      lineHeight: '1.600em',
      textAlign: 'left',
    },
    body_short: {
      color: 'var(--eds_paragraph__body_short_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      textAlign: 'left',
    },
    body_short_bold_italic: {
      color:
        'var(--eds_paragraph__body_short_bold_italic_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.250em',
      fontStyle: 'italic',
      textAlign: 'left',
    },
    body_short_bold: {
      color: 'var(--eds_paragraph__body_short_bold_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.250em',
      textAlign: 'left',
    },
    body_short_link: {
      color:
        'var(--eds_paragraph__body_short_link_color, rgba(0, 112, 121, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      textDecoration: 'underline',
      textAlign: 'left',
    },
    overline: {
      color: 'var(--eds_paragraph__overline_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.625rem',
      fontWeight: 500,
      letterSpacing: '0.069em',
      lineHeight: '1.600em',
      textTransform: 'uppercase',
      textAlign: 'left',
    },
    ingress: {
      color: 'var(--eds_paragraph__ingress_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.125rem',
      fontWeight: 400,
      lineHeight: '1.333em',
      textAlign: 'left',
    },
    body_long: {
      color: 'var(--eds_paragraph__body_long_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.500em',
      textAlign: 'left',
    },
    body_long_link: {
      color: 'var(--eds_paragraph__body_long_link_color, rgba(0, 112, 121, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.500em',
      textDecoration: 'underline',
      textAlign: 'left',
    },
    body_long_italic: {
      color:
        'var(--eds_paragraph__body_long_italic_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.500em',
      fontStyle: 'italic',
      textAlign: 'left',
    },
    body_long_bold: {
      color: 'var(--eds_paragraph__body_long_bold_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.500em',
      textAlign: 'left',
    },
    body_long_bold_italic: {
      color:
        'var(--eds_paragraph__body_long_bold_italic_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.500em',
      fontStyle: 'italic',
      textAlign: 'left',
    },
  },
  table: {
    cell_header: {
      color: 'var(--eds_table__cell_header_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 700,
      lineHeight: '1.429em',
      textAlign: 'left',
    },
    cell_text: {
      color: 'var(--eds_table__cell_text_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.429em',
      textAlign: 'left',
    },
    cell_text_bold: {
      color: 'var(--eds_table__cell_text_bold_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 700,
      lineHeight: '1.429em',
      textAlign: 'left',
    },
    cell_text_link: {
      color: 'var(--eds_table__cell_text_link_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.429em',
      textDecoration: 'underline',
      textAlign: 'left',
    },
    cell_numeric_monospaced: {
      fontFeature: "'tnum' on,'lnum' on",
      color:
        'var(--eds_table__cell_numeric_monospaced_color, rgba(0, 0, 0, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.429em',
      textAlign: 'left',
    },
  },
  _modes: {
    compact: {
      table: {
        cell_header: {
          color: 'var(--eds_table__cell_header_color, rgba(0, 0, 0, 1))',
          fontFamily: 'Equinor',
          fontSize: '0.875rem',
          fontWeight: 700,
          lineHeight: '1.143em',
          textAlign: 'left',
        },
        cell_text: {
          color: 'var(--eds_table__cell_text_color, rgba(0, 0, 0, 1))',
          fontFamily: 'Equinor',
          fontSize: '0.875rem',
          fontWeight: 500,
          lineHeight: '1.143em',
          textAlign: 'left',
        },
        cell_text_bold: {
          color: 'var(--eds_table__cell_text_bold_color, rgba(0, 0, 0, 1))',
          fontFamily: 'Equinor',
          fontSize: '0.875rem',
          fontWeight: 700,
          lineHeight: '1.143em',
          textAlign: 'left',
        },
        cell_text_link: {
          color: 'var(--eds_table__cell_text_link_color, rgba(0, 0, 0, 1))',
          fontFamily: 'Equinor',
          fontSize: '0.875rem',
          fontWeight: 500,
          lineHeight: '1.143em',
          textDecoration: 'underline',
          textAlign: 'left',
        },
        cell_numeric_monospaced: {
          fontFeature: "'tnum' on,'lnum' on",
          color:
            'var(--eds_table__cell_numeric_monospaced_color, rgba(0, 0, 0, 1))',
          fontFamily: 'Equinor',
          fontSize: '0.875rem',
          fontWeight: 500,
          lineHeight: '1.143em',
          textAlign: 'left',
        },
      },
    },
  },
  ui: {
    tooltip: {
      color: 'var(--eds_ui__tooltip_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      lineHeight: '1.333em',
      textAlign: 'left',
    },
    snackbar: {
      color: 'var(--eds_ui__snackbar_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      lineHeight: '1.333em',
      textAlign: 'left',
    },
    accordion_header: {
      color: 'var(--eds_ui__accordion_header_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      lineHeight: '1.500em',
      textAlign: 'left',
    },
    chip__badge: {
      color: 'var(--eds_ui__chip__badge_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      lineHeight: '1.55em',
      textAlign: 'left',
    },
    chart: {
      color: 'var(--eds_ui__chart_color, rgba(61, 61, 61, 1))',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      lineHeight: '1.333em',
      textAlign: 'left',
    },
  },
}
