const { BETA_CALLOUT, NUMBER_WORDS, PLATFORMS } = require('./config')
const { stripQuotes } = require('./text')
const { fencedCode } = require('./sidecar')
const { fail } = require('./errors')

// Pages are lists of blocks joined by a blank line. Optional blocks are
// falsy and dropped. Required sections (Features, Examples) are never dropped
// for being empty: the build fails instead, see the section helpers below.
const joinBlocks = (blocks) => `${blocks.filter(Boolean).join('\n\n')}\n`
const section = (title, body) => `## ${title}\n\n${body}`

// Turns a JSDoc value note ("Neutral gray tones (default)") into an inline
// aside ("neutral gray tones"). The default is stated separately.
function describeValue(note) {
  if (!note) return undefined
  const text = note.replace(/\s*\(default\)/, '').replace(/\.$/, '')
  return /^[A-Z][a-z]/.test(text)
    ? text.charAt(0).toLowerCase() + text.slice(1)
    : text
}

function renderFeatures(props) {
  return props
    .map((p) => {
      if (p.literals) {
        const count = NUMBER_WORDS[p.literals.length] ?? p.literals.length
        const values = p.literals
          .map((l) => {
            const note = describeValue(p.valueNotes[l])
            return note ? `\`${l}\` (${note})` : `\`${l}\``
          })
          .join(', ')
        const fallback = p.default
          ? ` The default is \`${stripQuotes(p.default)}\`.`
          : ''
        return `- ${count} \`${p.name}\` values: ${values}.${fallback}`
      }
      if (p.name === 'children') return `- Accepts \`${p.type}\` as children.`
      return `- ${p.description}`
    })
    .join('\n')
}

function renderPropsTable(props) {
  const rows = props.map((p) => {
    const type = p.type.replace(/\|/g, '\\|')
    const description = p.optional
      ? p.description
      : `${p.description} Required.`
    return `| \`${p.name}\` | \`${type}\` | ${p.default ? `\`${p.default}\`` : 'None'} | ${description} |`
  })
  return [
    '| Prop | Type | Default | Description |',
    '|---|---|---|---|',
    ...rows,
  ].join('\n')
}

// One Links row. `urls` is in display order, `indent` is for nesting.
function renderLinks(urls, indent = '') {
  const attrs = Object.entries(urls)
    .filter(([, value]) => value)
    .map(([name, value]) => `${indent}  ${name}="${value}"`)
    .join('\n')
  return `${indent}<Links\n${attrs}\n${indent}/>`
}

function generatedNote(component, relDir) {
  return `{/* Generated by scripts/generate-component-docs.js. Do not edit. Edit ${relDir}/${component}.docs.md, the ${component}Props type or ${component}.stories.tsx instead. */}`
}

// Sections both platforms share.
// Generated bullets first, then the hand-written ones from the sidecar. A
// component needs at least one of the two.
function featuresSection(component, ctx) {
  const bullets = [
    ctx.props.length ? renderFeatures(ctx.props) : null,
    ctx.sidecar.Features,
  ].filter(Boolean)
  if (!bullets.length) {
    fail(
      `${component}: no Features. ${component}Props declares no props of its own, so add a Features section to the sidecar.`,
    )
  }
  return section('Features', bullets.join('\n'))
}

function usageSection(component, platform, ctx) {
  const p = PLATFORMS[platform]
  return section(
    'Usage',
    `\`\`\`bash\n${p.installLine}\n\`\`\`\n\n\`\`\`tsx\n${p.importLine(component)}\n\n${fencedCode(ctx.sidecar.Usage)}\n\`\`\``,
  )
}

function examplesSection(component, examples) {
  if (!examples.length) {
    fail(
      `${component}: no Examples. ${component}.stories.tsx exports none besides the skipped playground story.`,
    )
  }
  return section('Examples', examples.join('\n\n'))
}

const closingSections = (ctx) => [
  section('Accessibility', ctx.sidecar.Accessibility),
  ctx.sidecar['Related components'] &&
    section('Related components', ctx.sidecar['Related components']),
]

// The React Native tab: plain markdown, no live demos.
function renderMobile(component, ctx) {
  const examples = ctx.stories.map((s) =>
    [s.title && `### ${s.title}`, s.caption, `\`\`\`tsx\n${s.code}\n\`\`\``]
      .filter(Boolean)
      .join('\n\n'),
  )
  return joinBlocks([
    generatedNote(component, ctx.relDir),
    featuresSection(component, ctx),
    usageSection(component, 'mobile', ctx),
    section(
      'Props',
      ctx.props.length
        ? renderPropsTable(ctx.props)
        : `${component} has no props of its own.`,
    ),
    examplesSection(component, examples),
    ...closingSections(ctx),
  ])
}

// The Storybook page: the web docs, with the React Native tab when a mobile
// sidecar exists.
function renderWeb(component, ctx) {
  const p = PLATFORMS.web
  const links = renderLinks({
    figmaUrl: ctx.figmaUrl,
    documentationUrl: ctx.docsUrl,
    ariaUrl: ctx.ariaUrl,
    sourceUrl: ctx.sourceUrl,
    npmUrl: p.npmUrl,
  })
  const examples = ctx.stories.map((s) =>
    [`### ${s.title}`, s.caption, `<Canvas of={Stories.${s.name}} />`]
      .filter(Boolean)
      .join('\n\n'),
  )
  const storybookImports = [
    "import { Meta, Primary, Controls, Canvas } from '@storybook/addon-docs/blocks'",
    `import * as Stories from './${component}.stories'`,
    ctx.hasMobile
      ? "import { Links, PlatformTabs } from './../../../../.storybook/components'"
      : "import { Links } from './../../../../.storybook/components'",
    ctx.hasMobile &&
      `import MobileDocs from '@equinor/eds-mobile-components/docs/${component}.mdx'`,
  ]
  const mobileLinks = renderLinks(
    {
      figmaUrl: ctx.figmaUrl,
      documentationUrl: ctx.docsUrl,
      sourceUrl: ctx.mobileSourceUrl,
      npmUrl: PLATFORMS.mobile.npmUrl,
    },
    '  ',
  )
  return joinBlocks([
    generatedNote(component, ctx.relDir),
    storybookImports.filter(Boolean).join('\n'),
    '<Meta of={Stories} />',
    `# ${component}`,
    ctx.sidecar.Summary,
    BETA_CALLOUT,
    ctx.hasMobile &&
      `<PlatformTabs mobile={<>\n${mobileLinks}\n  <MobileDocs />\n</>}>`,
    links,
    featuresSection(component, ctx),
    usageSection(component, 'web', ctx),
    section('Props and playground', '<Primary />\n<Controls />'),
    examplesSection(component, examples),
    ...closingSections(ctx),
    ctx.hasMobile && '</PlatformTabs>',
  ])
}

module.exports = {
  describeValue,
  renderFeatures,
  renderPropsTable,
  renderLinks,
  renderWeb,
  renderMobile,
}
