export const typography = {
  heading: {
    h1_bold: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '2.000rem',
      fontWeight: 700,
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
    h1: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '2.000rem',
      fontWeight: 400,
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
    h2: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.750rem',
      fontWeight: 400,
      lineHeight: '1.429em',
      textAlign: 'LEFT',
    },
    h3: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.500rem',
      fontWeight: 400,
      lineHeight: '1.667em',
      textAlign: 'LEFT',
    },
    h4: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.250rem',
      fontWeight: 400,
      lineHeight: '1.600em',
      textAlign: 'LEFT',
    },
    h5: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.125rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.333em',
      textAlign: 'LEFT',
    },
    h6: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
  },
  navigation: {
    menu_title: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      letterSpacing: '0.013em',
      lineHeight: '1.000em',
      textAlign: 'LEFT',
    },
    menu_tabs: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.000em',
      textAlign: 'LEFT',
    },
    label: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.688rem',
      fontWeight: 400,
      lineHeight: '1.455em',
      textAlign: 'LEFT',
    },
    drawer_active: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      letterSpacing: '0.006em',
      lineHeight: '1.000em',
      textAlign: 'LEFT',
    },
    drawer_inactive: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      letterSpacing: '0.013em',
      lineHeight: '1.000em',
      textAlign: 'LEFT',
    },
    button: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'LEFT',
    },
    breadcrumb: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textAlign: 'LEFT',
    },
    breadcrumb_hover: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.143em',
      textDecoration: 'UNDERLINE',
      textAlign: 'LEFT',
    },
  },
  input: {
    label: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 400,
      lineHeight: '1.333em',
      textAlign: 'LEFT',
    },
    text: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      letterSpacing: '0.025em',
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
    text_monospaced: {
      fontFeature: "'tnum' on, 'lnum' on",
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      letterSpacing: '0.063em',
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
    helper: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.688rem',
      fontWeight: 400,
      letterSpacing: '0.013em',
      lineHeight: '1.455em',
      textAlign: 'LEFT',
    },
  },
  paragraph: {
    body_short_italic: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      fontStyle: 'italic',
      textAlign: 'LEFT',
    },
    caption: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: '1.143em',
      textAlign: 'LEFT',
    },
    meta: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.625rem',
      fontWeight: 400,
      lineHeight: '1.600em',
      textAlign: 'LEFT',
    },
    body_short: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      textAlign: 'LEFT',
    },
    body_short_bold_italic: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.250em',
      fontStyle: 'italic',
      textAlign: 'LEFT',
    },
    body_short_bold: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.250em',
      textAlign: 'LEFT',
    },
    body_short_link: {
      color: 'rgba(0, 112, 121, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.250em',
      textDecoration: 'UNDERLINE',
      textAlign: 'LEFT',
    },
    overline: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.625rem',
      fontWeight: 500,
      letterSpacing: '0.069em',
      lineHeight: '1.600em',
      textTransform: 'UPPERCASE',
      textAlign: 'LEFT',
    },
    ingress: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.125rem',
      fontWeight: 400,
      lineHeight: '1.333em',
      textAlign: 'LEFT',
    },
    body_long: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
    body_long_link: {
      color: 'rgba(0, 112, 121, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.500em',
      textDecoration: 'UNDERLINE',
      textAlign: 'LEFT',
    },
    body_long_italic: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 400,
      lineHeight: '1.500em',
      fontStyle: 'italic',
      textAlign: 'LEFT',
    },
    body_long_bold: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
    body_long_bold_italic: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 700,
      lineHeight: '1.500em',
      fontStyle: 'italic',
      textAlign: 'LEFT',
    },
  },
  table: {
    cell_header: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 500,
      lineHeight: '1.714em',
      textAlign: 'LEFT',
    },
    cell_text: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: '1.714em',
      textAlign: 'LEFT',
    },
    cell_text_bold: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 700,
      lineHeight: '1.714em',
      textAlign: 'LEFT',
    },
    cell_text_link: {
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: '1.714em',
      textDecoration: 'UNDERLINE',
      textAlign: 'LEFT',
    },
    cell_numeric_monospaced: {
      fontFeature: "'tnum' on, 'lnum' on",
      color: 'rgba(0, 0, 0, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: '1.429em',
      textAlign: 'LEFT',
    },
  },
  ui: {
    tooltip: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 500,
      lineHeight: '1.333em',
      textAlign: 'LEFT',
    },
    snackbar: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 400,
      lineHeight: '1.333em',
      textAlign: 'LEFT',
    },
    accordion_header: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '1.000rem',
      fontWeight: 500,
      lineHeight: '1.500em',
      textAlign: 'LEFT',
    },
    chip__badge: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 400,
      lineHeight: '1.333em',
      textAlign: 'LEFT',
    },
    chart: {
      color: 'rgba(61, 61, 61, 1)',
      fontFamily: 'Equinor',
      fontSize: '0.750rem',
      fontWeight: 400,
      lineHeight: '1.333em',
      textAlign: 'LEFT',
    },
  },
}
