/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const density = {
  cornerRadius: {
    none: 0,
    pill: 9999,
    rounded: 2,
    roundedOuter: 4,
  },
  spacing: {
    twoXl: 24,
    twoXs: 4,
    threeXl: 28,
    threeXs: 2,
    fourXs: 1,
    lg: 16,
    md: 12,
    none: 0,
    sm: 10,
    xl: 20,
    xs: 6,
  },
  typography: {
    header: {
      twoXl: {
        fontSize: 21,
        lineHeight: 24,
      },
      threeXl: {
        fontSize: 24,
        lineHeight: 28,
      },
      fourXl: {
        fontSize: 28,
        lineHeight: 32,
      },
      lg: {
        fontSize: 16,
        lineHeight: 20,
      },
      md: {
        fontSize: 14,
        lineHeight: 16,
      },
      sm: {
        fontSize: 12,
        lineHeight: 16,
      },
      xl: {
        fontSize: 18,
        lineHeight: 24,
      },
      xs: {
        fontSize: 10,
        lineHeight: 12,
      },
    },
    ui: {
      twoXl: {
        fontSize: 18,
        lineHeight: 24,
      },
      threeXl: {
        fontSize: 21,
        lineHeight: 28,
      },
      fourXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      fiveXl: {
        fontSize: 28,
        lineHeight: 32,
      },
      lg: {
        fontSize: 14,
        lineHeight: 20,
      },
      md: {
        fontSize: 12,
        lineHeight: 16,
      },
      sm: {
        fontSize: 10,
        lineHeight: 16,
      },
      xl: {
        fontSize: 16,
        lineHeight: 24,
      },
      xs: {
        fontSize: 9,
        lineHeight: 12,
      },
    },
  },
} as const

export type Density = typeof density
