/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const density = {
  cornerRadius: {
    none: 0,
    pill: 9999,
    rounded: 6,
    roundedOuter: 8,
  },
  spacing: {
    twoXl: 32,
    twoXs: 8,
    threeXl: 36,
    threeXs: 6,
    fourXs: 4,
    lg: 24,
    md: 20,
    none: 0,
    sm: 16,
    xl: 28,
    xs: 10,
  },
  typography: {
    header: {
      twoXl: {
        fontSize: 28,
        lineHeight: 32,
      },
      threeXl: {
        fontSize: 32,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 36,
        lineHeight: 36,
      },
      lg: {
        fontSize: 21,
        lineHeight: 24,
      },
      md: {
        fontSize: 18,
        lineHeight: 24,
      },
      sm: {
        fontSize: 16,
        lineHeight: 20,
      },
      xl: {
        fontSize: 24,
        lineHeight: 28,
      },
      xs: {
        fontSize: 14,
        lineHeight: 16,
      },
    },
    ui: {
      twoXl: {
        fontSize: 24,
        lineHeight: 32,
      },
      threeXl: {
        fontSize: 28,
        lineHeight: 32,
      },
      fourXl: {
        fontSize: 32,
        lineHeight: 36,
      },
      fiveXl: {
        fontSize: 37,
        lineHeight: 40,
      },
      lg: {
        fontSize: 18,
        lineHeight: 24,
      },
      md: {
        fontSize: 16,
        lineHeight: 24,
      },
      sm: {
        fontSize: 14,
        lineHeight: 20,
      },
      xl: {
        fontSize: 21,
        lineHeight: 28,
      },
      xs: {
        fontSize: 12,
        lineHeight: 16,
      },
    },
  },
} as const

export type Density = typeof density
