/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const elevation = {
  shadow: {
    high: {
      ambient: {
        blur: 16,
        color: '#0000001f',
        spread: 6,
        x: 0,
        y: 12,
      },
      key: {
        blur: 12,
        color: '#00000033',
        spread: 0,
        x: 0,
        y: 4,
      },
    },
    low: {
      ambient: {
        blur: 8,
        color: '#0000001f',
        spread: 3,
        x: 0,
        y: 4,
      },
      key: {
        blur: 8,
        color: '#00000033',
        spread: 0,
        x: 0,
        y: 1,
      },
    },
  },
} as const

export type Elevation = typeof elevation
