import React from 'react'
import { Checkbox } from './Checkbox'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/dz0XQdc5j7AAtjXr1gTfVR/EDS-Core-Components?node-id=112-5454&t=i0mpjmASoWqCfkG9-11',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum('State', {
        Disabled: true,
      }),
      indeterminate: figma.enum('Indeterminate', {
        false: false,
        true: true,
      }),
      checked: figma.boolean('Is Checked'),
      readOnly: figma.enum('State', {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "showFocusFrame": figma.boolean('Show focus frame')
    },
    example: (props) => (
      <Checkbox
        disabled={props.disabled}
        indeterminate={props.indeterminate}
        checked={props.checked}
        readOnly={props.readOnly}
      />
    ),
  },
)
