import { Button } from './Button'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  'https://www.figma.com/design/dz0XQdc5j7AAtjXr1gTfVR/EDS-Core-Components?node-id=18-1193',
  {
    props: {
      color: figma.enum('Tone', {
        Accent: 'primary',
        Neutral: 'secondary',
        Danger: 'danger',
      }),
      baseButton: figma.nestedProps('⌘ Button', {
        label: figma.textContent('Label Text'),
        variant: figma.enum('Variant', {
          Primary: 'contained',
          Secondary: 'outlined',
          Ghost: 'ghost',
        }),
        LeadingIcon: figma.boolean('Show Leading Icon', {
          true: figma.children('Leading Icon Item'),
          false: undefined,
        }),
        TrailingIcon: figma.boolean('Show Trailing Icon', {
          true: figma.children('Trailing Icon Item'),
          false: undefined,
        }),
      }),
    },
    example: ({ color, baseButton }) => (
      <Button color={color} variant={baseButton.variant}>
        {baseButton.LeadingIcon}
        {baseButton.label}
        {baseButton.TrailingIcon}
      </Button>
    ),
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */
//Icon Button
figma.connect(
  Button,
  'https://www.figma.com/design/dz0XQdc5j7AAtjXr1gTfVR/EDS-Core-Components?node-id=18%3A1373',
  {
    props: {
      geometry: figma.nestedProps('Geometry Options', {}),
      baseButton: figma.nestedProps('↳ ⌘ Button', {
        variant: figma.enum('Variant', {
          Primary: 'contained',
          Secondary: 'outlined',
          Ghost: 'ghost',
        }),
      }),

      // No matching props could be found for these Figma properties:
      // "tone": figma.enum('Tone', {
      //   "Accent": "accent",
      //   "Neutral": "neutral",
      //   "Danger": "danger"
      /// ⌘ Button
      // })
    },
    example: ({ baseButton }) => <Button variant={baseButton.variant} />,
  },
)
