name: Sync tokens to Figma
on:
  workflow_dispatch:
jobs:
  sync-tokens-to-figma:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: packages/tokens-sync

      - name: Sync tokens to Figma file
        run: npm run sync-tokens-to-figma
        working-directory: packages/tokens-sync
        env:
          FILE_KEY: ${{ github.event.inputs.file_key }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_ACTION_VARIABLES_SYNC_FIGMA_TOKEN }}
