FROM node:15 as builder

# for debugging
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends fish neovim

WORKDIR /app

RUN npm install -g pnpm

COPY ./package.yaml ./
COPY ./pnpm-workspaces.yaml ./
COPY ./.npmrc ./
COPY ./pnpm-lock.yaml ./
COPY ./tsconfig.base.json ./

WORKDIR /app/apps
COPY ./apps/storybook-react ./storybook

WORKDIR /app/apps/storybook/libraries

COPY ./libraries/core-react ./eds-core-react
COPY ./libraries/tokens ./eds-tokens
COPY ./libraries/icons ./eds-icons

WORKDIR /app
RUN pnpm --filter ./apps/storybook remove \
  @equinor/eds-core-react \
  @equinor/eds-tokens \
  @equinor/eds-icons

WORKDIR /app/apps/storybook
RUN pnpm run build

FROM nginx:1.15.8-alpine
WORKDIR /app
COPY --from=builder /app/apps/storybook/dist /app
COPY ./apps/storybook-react/nginx.conf /etc/nginx/conf.d/default.conf
