FROM node:12 as builder
WORKDIR /app

# install pnpm
RUN npm install -g pnpm

COPY ./package.yaml ./
COPY ./pnpm-workspaces.yaml ./
COPY ./.npmrc ./

# copy libraries
WORKDIR /app/libraries
COPY ./libraries/tokens ./tokens
COPY ./libraries/core-react ./core-react
COPY ./libraries/icons ./icons

# copy storybook
WORKDIR /app/apps
COPY ./apps/storybook-react ./storybook-react

# build storybook and dependencies
WORKDIR /app
RUN pnpm --filter @equinor/eds-core-react install && \
  pnpm --filter @equinor/eds-core-react run build

RUN pnpm --filter @equinor/eds-tokens run build
RUN pnpm --filter @equinor/eds-icons run build

RUN pnpm --filter @equinor/eds-storybook-react install

# build storybook
RUN pnpm --filter @equinor/eds-storybook-react run build
RUN mv ./apps/storybook-react/dist ./storybook

# host
FROM nginx:1.15.8-alpine
WORKDIR /app
COPY --from=builder ./app/storybook /app
COPY ./apps/storybook-react/nginx.conf /etc/nginx/conf.d/default.conf
