FROM node:14-buster as builder

# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  # && apt-get -y install --no-install-recommends fish neovim

WORKDIR /app

# install pnpm
RUN npm install -g pnpm

COPY ./package.yaml ./
COPY ./pnpm-workspaces.yaml ./
COPY ./.npmrc ./
COPY ./pnpm-lock.yaml ./
COPY ./tsconfig.base.json ./

# copy libraries
WORKDIR /app/libraries
COPY ./libraries/tokens ./tokens
COPY ./libraries/core-react ./core-react
COPY ./libraries/icons ./icons

# copy storybook
WORKDIR /app/apps
COPY ./apps/storybook-react ./storybook-react

# build storybook
WORKDIR /app
RUN pnpm m i && pnpm build:storybook
RUN mv ./apps/storybook-react/dist ./storybook

# host
FROM nginx:1.15.8-alpine
WORKDIR /app
COPY --from=builder ./app/storybook /app
COPY ./apps/storybook-react/nginx.conf /etc/nginx/conf.d/default.conf
