import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
//Create as many sidebars as you want.
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  aboutSidebar: [
    'about/about_eds',
    {
      type: 'category',
      label: 'Basics',
      link: {
        type: 'doc',
        id: 'about/getting-started/getting_started',
      },
      items: [
        'about/getting-started/getting_started',
        {
          type: 'category',
          label: 'Design',
          link: {
            type: 'doc',
            id: 'about/getting-started/design/getting_started_design'
          },
          items: [
            'about/getting-started/design/getting_started_design',
            'about/getting-started/design/Figma',
          ],
        },
        {
          type: 'category',
          label: 'Develop',
          link: {
            type: 'doc',
            id: 'about/getting-started/develop/getting_started_development'
          },
          items: [
            'about/getting-started/develop/getting_started_development',
            'about/getting-started/develop/citizen_developers',

          ],
        },

        'about/getting-started/team_roles',
      ],
    },
    'about/team/team',
  ],
  componentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'components',
    },
  ],
  foundationSidebar: [{ type: 'autogenerated', dirName: 'foundation' }],
  resourcesSidebar: [{ type: 'autogenerated', dirName: 'resources' }],
  supportSidebar: [{ type: 'autogenerated', dirName: 'support' }],
}

export default sidebars
