import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
//Create as many sidebars as you want.
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  aboutSidebar: [
    {
      type: 'autogenerated',
      dirName: 'about',
    },
  ],
  componentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'components',
    },
  ],
  foundationSidebar: [{ type: 'autogenerated', dirName: 'foundation' }],
  resourcesSidebar: [{ type: 'autogenerated', dirName: 'resources' }],
  supportSidebar: [{ type: 'autogenerated', dirName: 'support' }],
}

export default sidebars
