import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
//Create as many sidebars as you want.
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  //About Section
  aboutSidebar: [
    'about/about_eds',
    {
      type: 'category',
      label: 'Basics',
      link: {
        type: 'doc',
        id: 'about/getting-started/getting_started',
      },
      items: [
        'about/getting-started/getting_started',
        {
          type: 'category',
          label: 'Design',
          link: {
            type: 'doc',
            id: 'about/getting-started/design/getting_started_design',
          },
          items: [
            'about/getting-started/design/getting_started_design',
            'about/getting-started/design/figma',
          ],
        },
        {
          type: 'category',
          label: 'Develop',
          link: {
            type: 'doc',
            id: 'about/getting-started/develop/getting_started_development',
          },
          items: [
            'about/getting-started/develop/getting_started_development',
            'about/getting-started/develop/citizen_developers',
          ],
        },

        'about/getting-started/team_roles',
      ],
    },
    'about/team/team',
  ],
  //Components Section
  componentsSidebar: [
    'components/components',
    {
      type: 'category',
      label: 'Inputs',
      link: {
        type: 'doc',
        id: 'components/inputs/autocomplete',
      },
      items: [
        'components/inputs/button',
        'components/inputs/input',
        'components/inputs/selection_controls',
        'components/inputs/field',
        'components/inputs/textfield',
      ],
    },
  ],
  //Foundation Section
  foundationSidebar: [
    'foundation/accessibility',
    {
      type: 'category',
      label: 'Colour',
      link: {
        type: 'doc',
        id: 'foundation/colour/intro',
      },
      items: ['foundation/colour/intro', 'foundation/colour/getting_started'],
    },
    {
      type: 'category',
      label: 'Design Tokens',
      link: {
        type: 'doc',
        id: 'foundation/design-tokens/grid',
      },
      items: [
        'foundation/design-tokens/grid',
        'foundation/design-tokens/elevation',
        'foundation/design-tokens/shape',
        'foundation/design-tokens/spacing',
        'foundation/design-tokens/typography',
      ],
    },
    'foundation/datavisualisation',
    'foundation/patterns',
    {
      type: 'category',
      label: 'Assets',
      link: {
        type: 'doc',
        id: 'foundation/assets/image_placeholder',
      },
      items: [
        'foundation/assets/image_placeholder',
        'foundation/assets/logos',
        'foundation/assets/illustration',
        'foundation/assets/product_icons',
        'foundation/assets/system_icons',
        'foundation/assets/photography',
      ],
    },
  ],
  //Resources Section
  resourcesSidebar: [{ type: 'autogenerated', dirName: 'resources' }],
  //Support Section
  supportSidebar: [{ type: 'autogenerated', dirName: 'support' }],
}

export default sidebars
