
name: $(Build.BuildId)

trigger:
  batch: "true"
  paths:
    include:
    # This cant be a variable
      - apps/figma-broker/*


variables:
  imageName: 'eds-figma-broker:$(Build.BuildId)-$(Build.SourceBranchName)'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: 'eds-rg-dev'
    azureContainerRegistry: edscontainers.azurecr.io
    imageName: '$(imageName)'
    includeLatestTag: true
    command: Build an image
  env:
    BUILD_DATE: $(Date:yyyyMMdd)

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'eds-rg-dev'
    azureContainerRegistry: edscontainers.azurecr.io
    command: Push an image
    imageName: '$(imageName)'
