name: eds-figma-broker-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: 'true'
  branches:
    include:
      - develop
  paths:
    include:
      - apps/figma-broker

pr:
  branches:
    include:
      - develop
  paths:
    include:
      - apps/figma-broker

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install -g pnpm@next
    displayName: 'Install pnpm'

  - script: pnpm --filter ./apps/figma-broker install
    displayName: 'Install dependencies'

  - script: pnpm --filter ./apps/figma-broker run build
    displayName: 'Run build'

  - script: >-
      ./node_modules/eslint/bin/eslint.js
      ./apps/figma-broker/**/*.js
      --no-ignore
      --ignore-pattern 'node_modules'
    displayName: 'Run eslint'
