# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: eds-static-$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: "true"
  branches:
    include:
    - develop
    - feature/eds-static
  paths:
    include:
      - libraries/eds-static

pr:
  branches:
    include:
    - develop
    - feature/eds-static
  paths:
    include:
    - libraries/eds-static



variables:
- group: eds-build-tokens
- name: ROOTFOLDER
  value: /libraries/eds-static

steps:

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '8.x'

- script: curl -L https://unpkg.com/@pnpm/self-installer | node
  displayName: 'Install pnpm'

- script: EQUINOR_INTERNAL_NPM_TOKEN=$(EQUINOR_INTERNAL_NPM_TOKEN) pnpm --filter .$(ROOTFOLDER) install --frozen-lockfile --registry=https://npm.equinor.com
  displayName: 'pnpm install'

- script: pnpm --filter .$(ROOTFOLDER) run build
  displayName: 'pnpm run build'

- script: ls -la .$(ROOTFOLDER)
  displayName: ls -la
