name: eds-static
description: Files published to eds-static.equinor.com
scripts:
  build: pnpm run copyfont & pnpm run copylogo
  copyfont: >-
    copyfiles --flat 'node_modules/@equinor-internal/equinor-font/dist/*' dist/font & >-
    copyfiles --flat 'node_modules/@equinor-internal/equinor-?(light|regular|medium|bold)?(italic)/*.css' dist/font
  copylogo: copyfiles --flat 'node_modules/@equinor-internal/equinor-logo/*.svg' dist/logo
dependencies:
  '@equinor-internal/equinor-bold': ^2.0.0
  '@equinor-internal/equinor-bolditalic': ^2.0.0
  '@equinor-internal/equinor-font': ^2.0.0
  '@equinor-internal/equinor-italic': ^2.0.0
  '@equinor-internal/equinor-light': ^2.0.0
  '@equinor-internal/equinor-lightitalic': ^2.0.0
  '@equinor-internal/equinor-logo': ^1.0.6
  '@equinor-internal/equinor-medium': ^2.0.0
  '@equinor-internal/equinor-mediumitalic': ^2.0.0
  '@equinor-internal/equinor-regular': ^2.0.0
devDependencies:
  copyfiles: ^2.1.1
