/**
 * Do not edit directly — generated by scripts/generate-ts-tokens.mjs
 * from the Tokens Studio DTCG + CSS exports.
 */

export const primitives = {
  fontFamily: {
    equinor: 'Equinor',
    inter: 'Inter',
  },
  lineheightScale: {
    '100': {
      default: 12,
    },
    '200': {
      default: 16,
    },
    '300': {
      default: 16,
    },
    '400': {
      default: 20,
    },
    '500': {
      default: 24,
    },
    '600': {
      default: 24,
    },
    '700': {
      default: 28,
    },
    '800': {
      default: 32,
    },
    '900': {
      default: 32,
    },
    '1000': {
      default: 36,
    },
    '1100': {
      default: 40,
    },
  },
  spacing: {
    '0': 0,
    '6': 1,
    '12': 2,
    '19': 3,
    '25': 4,
    '37': 6,
    '50': 8,
    '62': 10,
    '75': 12,
    '87': 14,
    '100': 16,
    '125': 20,
    '150': 24,
    '175': 28,
    '200': 32,
    '225': 36,
    '250': 40,
    '275': 44,
    '300': 48,
    '325': 52,
    '350': 56,
    '375': 60,
    '400': 64,
    '450': 72,
    '500': 80,
    '550': 88,
    '600': 96,
    '700': 112,
    '800': 128,
    '900': 144,
    '1000': 160,
    '1100': 176,
    '1200': 192,
    '1300': 208,
    '1400': 224,
    '1500': 240,
    '1600': 256,
    '1700': 272,
    '1800': 288,
    '1900': 304,
    '2000': 320,
    '2100': 336,
    '2200': 352,
  },
  typeScale: {
    equinor: {
      '100': {
        fontSize: 10,
      },
      '200': {
        fontSize: 12,
      },
      '300': {
        fontSize: 14,
      },
      '400': {
        fontSize: 16,
      },
      '500': {
        fontSize: 18,
      },
      '600': {
        fontSize: 21,
      },
      '700': {
        fontSize: 24,
      },
      '800': {
        fontSize: 28,
      },
      '900': {
        fontSize: 32,
      },
      '1000': {
        fontSize: 36,
      },
      '1100': {
        fontSize: 42,
      },
    },
    inter: {
      '100': {
        fontSize: 9,
      },
      '200': {
        fontSize: 10,
      },
      '300': {
        fontSize: 12,
      },
      '400': {
        fontSize: 14,
      },
      '500': {
        fontSize: 16,
      },
      '600': {
        fontSize: 18,
      },
      '700': {
        fontSize: 21,
      },
      '800': {
        fontSize: 24,
      },
      '900': {
        fontSize: 28,
      },
      '1000': {
        fontSize: 32,
      },
      '1100': {
        fontSize: 37,
      },
    },
    trackingNormal: 0,
  },
  weightScale: {
    bolder: 500,
    lighter: 300,
    normal: 400,
  },
} as const

export type Primitives = typeof primitives
