#!/usr/bin/env ts-node
/*
 * Script: generate-palette-overview.ts
 * Purpose: Regenerate PALETTE_OVERVIEW.md from src/config/config.ts
 * Usage: pnpm generate:palette
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { PALETTE_STEPS } from '../src/config/config'
import { APCA_CONTRAST_LEVELS } from '../src/config/APCA_CONTRAST_LEVELS'
import { WCAG_CONTRAST_LEVELS } from '../src/config/WCAG_CONTRAST_LEVELS'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

interface ContrastRow {
  pairing: string
  foreground: string
  background: string
  apca: number
  wcagKey: string
  wcagValue: number
}

const outPath = path.join(__dirname, '..', 'PALETTE_OVERVIEW.md')

function mdEscape(text: string) {
  return text.replace(/\\/g, '\\\\').replace(/\|/g, '\\|')
}

function formatNumber(n: number, digits = 2) {
  return n.toFixed(digits)
}

function buildStepsTable() {
  const header =
    '| Step | Label | Main role (Tokens Studio) | Light (L) | Dark (L) |'
  const sep =
    '| ---- | ----- | ------------------------- | --------- | -------- |'
  const rows = PALETTE_STEPS.map((s) =>
    [
      s.step,
      s.label,
      s.primaryRole ?? '(none)',
      formatNumber(s.lightValue, 2),
      formatNumber(s.darkValue, 2),
    ]
      .map((v) => mdEscape(String(v)))
      .join(' | '),
  )
  return [header, sep, ...rows.map((r) => `| ${r} |`)].join('\n')
}

function buildContrastRows(): ContrastRow[] {
  const rows: ContrastRow[] = []
  PALETTE_STEPS.forEach((s) => {
    s.contrastWith?.forEach((req) => {
      // Match the level object itself; several levels share a ratio.
      const wcagKey =
        Object.keys(WCAG_CONTRAST_LEVELS).find(
          (k) =>
            WCAG_CONTRAST_LEVELS[k as keyof typeof WCAG_CONTRAST_LEVELS] ===
            req.wcag,
        ) || 'UNKNOWN'
      rows.push({
        pairing: req.pairing,
        foreground: s.id,
        background: req.targetStep,
        apca: req.lc.value,
        wcagKey,
        wcagValue: req.wcag.value,
      })
    })
  })
  return rows
}

function buildContrastTable() {
  const header =
    '| Pairing (Tokens Studio) | Foreground | Background | APCA | WCAG |'
  const sep =
    '| ----------------------- | ---------- | ---------- | ---- | ---- |'
  const rows = buildContrastRows().map(
    (r) =>
      `| \`${r.pairing}\` | ${r.foreground} | ${r.background} | ${r.apca} | ${r.wcagKey} (${r.wcagValue}) |`,
  )
  return [header, sep, ...rows].join('\n')
}

function buildApcaLevelsTable() {
  const header = '| Key | LC Value | Description |'
  const sep = '| --- | -------- | ----------- |'
  const rows = Object.entries(APCA_CONTRAST_LEVELS).map(
    ([key, val]) => `| ${key} | ${val.value} | ${mdEscape(val.description)} |`,
  )
  return [header, sep, ...rows].join('\n')
}

function buildWcagLevelsTable() {
  const header = '| Key | Ratio | Description |'
  const sep = '| --- | ----- | ----------- |'
  const rows = Object.entries(WCAG_CONTRAST_LEVELS).map(
    ([key, val]) => `| ${key} | ${val.value} | ${mdEscape(val.description)} |`,
  )
  return [header, sep, ...rows].join('\n')
}

function generate() {
  const date = new Date().toISOString().split('T')[0]
  const content = `# EDS colour palette configuration overview\n\n_Generated overview of the palette configuration: step values and roles from Tokens Studio, contrast requirements from ADR 0016, and reference contrast levels._\n\nGenerated: ${date}\n\n## Step Definitions\n\n${buildStepsTable()}\n\n## Contrast requirements (foreground → background)\n\n_APCA Lc is the required lightness contrast (ADR 0016 Confirmation 5). The WCAG column shows the reference level and ratio._\n\n${buildContrastTable()}\n\n## APCA Contrast Levels Reference\n\n${buildApcaLevelsTable()}\n\n## WCAG Contrast Levels Reference\n\n${buildWcagLevelsTable()}\n\n---\n\n_This document is generated by \`pnpm generate:palette-config-in-markdown\`. Lightness and roles come from Tokens Studio (\`src/config/tokensStudio.ts\`); change them there. The step labels and contrast requirements are in \`src/config/config.ts\`._\n`
  fs.writeFileSync(outPath, content, 'utf8')
  console.log(
    `Palette overview generated -> ${path.relative(process.cwd(), outPath)}`,
  )
}

generate()
