name: Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/eds-core-react/**'
      - 'packages/eds-lab-react/**'
      - 'packages/eds-tokens/**'
      - 'packages/eds-icons/**'
  push:
    branches:
      - develop
env:
  CACHE_KEY: ${{ github.sha }-core
jobs:
  setup:
    uses: equinor/design-system/.github/workflows/setup.yml@develop
    with:
      cacheKey: ${{ env.CACHE_KEY }}
    secrets:
      npmToken: ${{ secrets.NPM_TOKEN }}
  packages:
    name: Prepare packages
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Use "setup" cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ env.CACHE_KEY }}
      - name: Use "packages" cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ env.CACHE_KEY }}-packages
      - name: Build packages
        run: node_modules/.bin/pnpm run build
      - name: Test packages
        run: node_modules/.bin/pnpm run test
      - name: Lint packages
        run: node_modules/.bin/pnpm run lint:all
      - name: Run type checks in core-react
        run: node_modules/.bin/tsc -p ./packages/eds-core-react
      - name: Run type checks in tokens
        run: node_modules/.bin/tsc -p ./packages/eds-icons
      - name: Run type checks in icons
        run: node_modules/.bin/tsc -p ./packages/eds-tokens
      - name: Run type checks in utils
        run: node_modules/.bin/tsc -p ./packages/eds-utils

  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Use "packages" cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ env.CACHE_KEY }}-packages
      - name: Build storybook
        run: node_modules/.bin/pnpm --filter @equinor/eds-core-react run build:storybook
