name: Checks lab
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths:
      - 'packages/eds-lab-react/**'
      - 'packages/eds-utils/**'
  push:
    branches:
      - develop
jobs:
  setup:
    uses: equinor/design-system/.github/workflows/setup.yml@develop
    with:
      cacheKey: ${{ github.sha }}-lab
    secrets:
      npmToken: ${{ secrets.NPM_TOKEN }}
  build-tokens:
    name: Build eds-tokens
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get base files
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-lab
      - name: Build
        run: node_modules/.bin/pnpm --filter @equinor/eds-tokens run build
      - name: Save build to cache
        uses: actions/cache@v2
        with:
          path: ./packages/eds-tokens
          key: ${{ github.sha }}-build-tokens
  test-utils:
    name: Test eds-utils
    runs-on: ubuntu-latest
    needs: [build-tokens]
    steps:
      - uses: actions/cache@v2
        name: Get base files
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-lab
      - name: Get eds-tokens build
        uses: actions/cache@v2
        with:
          path: ./packages/eds-tokens
          key: ${{ github.sha }}-build-tokens
      - name: Test eds-utils
        run: node_modules/.bin/pnpm --filter @equinor/eds-utils run test
  build-utils:
    name: Build eds-utils
    runs-on: ubuntu-latest
    needs: [test-utils]
    steps:
      - uses: actions/cache@v2
        name: Get base files
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-lab
      - name: Get eds-tokens build
        uses: actions/cache@v2
        with:
          path: ./packages/eds-tokens
          key: ${{ github.sha }}-build-tokens
      - name: Build
        run: node_modules/.bin/pnpm --filter @equinor/eds-utils run build
      - name: Save build to cache
        uses: actions/cache@v2
        with:
          path: ./packages/eds-utils
          key: ${{ github.sha }}-build-utils
  build-icons:
    name: Build eds-icons
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get base files
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-lab
      - name: Build
        run: node_modules/.bin/pnpm --filter @equinor/eds-icons run build
      - name: Save build to cache
        uses: actions/cache@v2
        with:
          path: ./packages/eds-icons
          key: ${{ github.sha }}-build-icons
  build-core-react:
    name: Build eds-core-react
    runs-on: ubuntu-latest
    needs: [build-icons, build-tokens, build-utils]
    steps:
      - uses: actions/cache@v2
        name: Get base files
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-lab
      - name: Get eds-utils build
        uses: actions/cache@v2
        with:
          path: ./packages/eds-utils
          key: ${{ github.sha }}-build-utils
      - name: Get eds-icons build
        uses: actions/cache@v2
        with:
          path: ./packages/eds-icons
          key: ${{ github.sha }}-build-icons
      - name: Get eds-tokens build
        uses: actions/cache@v2
        with:
          path: ./packages/eds-tokens
          key: ${{ github.sha }}-build-tokens
      - name: Build
        run: node_modules/.bin/pnpm --filter @equinor/eds-core-react run build
      - name: Save build to cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-build-core-react
  test:
    name: Test eds-lab-react
    runs-on: ubuntu-latest
    needs: [build-core-react]
    steps:
      - name: Get core-react build
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-build-core-react
      - name: Test eds-lab-react
        run: node_modules/.bin/pnpm --filter @equinor/eds-lab-react run test
  lint:
    name: Lint eds-lab-react
    runs-on: ubuntu-latest
    needs: [build-core-react]
    steps:
      - name: Get core-react build
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-build-core-react
      - name: Lint all packages
        run: node_modules/.bin/pnpm run lint ./packages
  types:
    name: Check types eds-lab-react
    runs-on: ubuntu-latest
    needs: [build-core-react]
    steps:
      - name: Get core-react build
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-build-core-react
      - name: Run type checks in lab
        run: node_modules/.bin/tsc -p ./packages/eds-lab-react
  build-lab:
    name: Build eds-lab-react
    runs-on: ubuntu-latest
    needs: [test, lint, types]
    steps:
      - uses: actions/cache@v2
        name: Get base files
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-lab
      - name: Get core-react build
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-build-core-react
      - name: Build
        run: node_modules/.bin/pnpm --filter @equinor/eds-lab-react run build
      - name: Save build to cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-build-lab
  build-storybook:
    name: Build lab Storybook
    runs-on: ubuntu-latest
    needs: [test, lint, types]
    steps:
      - name: Get core-react build
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-build-core-react
      - name: Build storybook
        run: node_modules/.bin/pnpm --filter @equinor/eds-lab-react run build:storybook
