# TODO: Create a composite action for publishing to simplify things
name: Publish icons
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      npm-tag:
        description: 'Tag for npm package (next | latest)'
        required: true
        type: choice
        options:
          - next
          - latest
        default: 'next'
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  setup:
    uses: ./.github/workflows/_setup.yml
    secrets: inherit
    with:
      cacheKey: ${{ github.sha }}-setup-icons
      checkout_paths: packages scripts
      tag: ${{ github.event.inputs.npm-tag }}
  packages:
    name: Process packages
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Use "setup" cache
        id: setup-cache
        uses: actions/cache@v6
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-setup-icons
      - name: Use "dist" cache
        id: dist-cache
        uses: actions/cache@v6
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-dist-production-icons
      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.16.0'
      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Build packages
        id: build-packages
        run: pnpm run build
      - name: log-errors-to-slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
  publish:
    name: Publish icons to npm
    runs-on: ubuntu-latest
    needs: [packages, setup]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Use "dist" cache
        id: dist-cache
        uses: actions/cache@v6
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-dist-production-icons
      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.16.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
      - name: Publish to npm
        id: publish-to-npm
        working-directory: packages/eds-icons
        run: pnpm publish --access public --provenance --tag ${{ needs.setup.outputs.tag }} --no-git-checks
      - name: log-errors-to-slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
