name: Trigger Package Publishing

on:
  pull_request:
    types: [closed]
    branches:
      # - develop TODO: enable after testing
      - fre/release-please

permissions:
  contents: write
  actions: write

jobs:
  check-releases:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.title, 'chore: release')
    runs-on: ubuntu-latest
    outputs:
      core-react: ${{ steps.check.outputs.core-react }}
      lab-react: ${{ steps.check.outputs.lab-react }}
      data-grid-react: ${{ steps.check.outputs.data-grid-react }}
      icons: ${{ steps.check.outputs.icons }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check which packages changed
        id: check
        run: |
          # Check if package.json files were modified in the PR
          if git diff HEAD~1 HEAD --name-only | grep -q "packages/eds-core-react/package.json"; then
            echo "core-react=true" >> $GITHUB_OUTPUT
          else
            echo "core-react=false" >> $GITHUB_OUTPUT
          fi

          if git diff HEAD~1 HEAD --name-only | grep -q "packages/eds-lab-react/package.json"; then
            echo "lab-react=true" >> $GITHUB_OUTPUT
          else
            echo "lab-react=false" >> $GITHUB_OUTPUT
          fi

          if git diff HEAD~1 HEAD --name-only | grep -q "packages/eds-data-grid-react/package.json"; then
            echo "data-grid-react=true" >> $GITHUB_OUTPUT
          else
            echo "data-grid-react=false" >> $GITHUB_OUTPUT
          fi

          if git diff HEAD~1 HEAD --name-only | grep -q "packages/eds-icons/package.json"; then
            echo "icons=true" >> $GITHUB_OUTPUT
          else
            echo "icons=false" >> $GITHUB_OUTPUT
          fi

  trigger-core-react:
    needs: check-releases
    if: needs.check-releases.outputs.core-react == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger core-react publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run publish-core-react.yml \
            --repo ${{ github.repository }} \
            --ref develop \
            -f npm-tag=latest \
            -f environment=production

  trigger-lab-react:
    needs: check-releases
    if: needs.check-releases.outputs.lab-react == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger lab-react publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run publish-lab-react.yml \
            --repo ${{ github.repository }} \
            --ref develop \
            -f npm-tag=latest \
            -f environment=production

  trigger-data-grid-react:
    needs: check-releases
    if: needs.check-releases.outputs.data-grid-react == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger data-grid-react publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run publish-data-grid-react.yml \
            --repo ${{ github.repository }} \
            --ref develop \
            -f npm-tag=latest \
            -f environment=production

  trigger-icons:
    needs: check-releases
    if: needs.check-releases.outputs.icons == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger icons publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run publish-icons.yml \
            --repo ${{ github.repository }} \
            --ref develop \
            -f npm-tag=latest
