name: Release Please

on:
  push:
    branches:
      # - develop  # TODO: enable after testing
      - fre/release-please # Test branch

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      eds-core-react--release_created: ${{ steps.release.outputs['packages/eds-core-react--release_created'] }}
      eds-core-react--tag_name: ${{ steps.release.outputs['packages/eds-core-react--tag_name'] }}
      eds-data-grid-react--release_created: ${{ steps.release.outputs['packages/eds-data-grid-react--release_created'] }}
      eds-data-grid-react--tag_name: ${{ steps.release.outputs['packages/eds-data-grid-react--tag_name'] }}
      eds-icons--release_created: ${{ steps.release.outputs['packages/eds-icons--release_created'] }}
      eds-icons--tag_name: ${{ steps.release.outputs['packages/eds-icons--tag_name'] }}
      eds-lab-react--release_created: ${{ steps.release.outputs['packages/eds-lab-react--release_created'] }}
      eds-lab-react--tag_name: ${{ steps.release.outputs['packages/eds-lab-react--tag_name'] }}
      eds-tokens--release_created: ${{ steps.release.outputs['packages/eds-tokens--release_created'] }}
      eds-tokens--tag_name: ${{ steps.release.outputs['packages/eds-tokens--tag_name'] }}
      eds-tokens-build--release_created: ${{ steps.release.outputs['packages/eds-tokens-build--release_created'] }}
      eds-tokens-build--tag_name: ${{ steps.release.outputs['packages/eds-tokens-build--tag_name'] }}
      eds-tokens-sync--release_created: ${{ steps.release.outputs['packages/eds-tokens-sync--release_created'] }}
      eds-tokens-sync--tag_name: ${{ steps.release.outputs['packages/eds-tokens-sync--tag_name'] }}
      eds-utils--release_created: ${{ steps.release.outputs['packages/eds-utils--release_created'] }}
      eds-utils--tag_name: ${{ steps.release.outputs['packages/eds-utils--tag_name'] }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          target-branch: fre/release-please #TODO: remove after testing
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print release outputs for debugging
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo "Releases created!"
          echo "${{ toJson(steps.release.outputs) }}"
