name: Setup
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
      stage:
        type: string
        required: false
      cacheKey:
        type: string
        required: true
    outputs:
      tag:
        description: 'Package tag'
        value: ${{ jobs.variables.outputs.tag }}
      stage:
        description: 'Stage'
        value: ${{ jobs.variables.outputs.stage }}
jobs:
  variables:
    runs-on: ubuntu-latest
    env:
      INPUT_STAGE: '${{ inputs.stage }}'
      INPUT_TAG: '${{ inputs.tag }}'
    outputs:
      stage: ${{ steps.input-stage.outputs.value }} ${{ steps.default-stage.outputs.value }}
      tag: ${{ steps.input-tag.outputs.slot }} ${{ steps.default-tag.outputs.value }}
    steps:
      - id: input-stage
        if: "${{ env.INPUT_STAGE != '' }}"
        run: echo "::set-output name=value::${{ env.INPUT_STAGE }}"
      - id: default-stage
        if: "${{ env.INPUT_STAGE == '' }}"
        run: echo "::set-output name=value::development"
      - id: input-tag
        if: "${{ env.INPUT_TAG != '' }}"
        run: echo "::set-output name=value::${{ env.INPUT_TAG }}"
      - id: default-tag
        if: "${{ env.INPUT_TAG == '' }}"
        run: echo "::set-output name=value::next"
  files:
    runs-on: ubuntu-latest
    steps:
      - id: cache-files
        name: Cache files
        uses: actions/cache@v3
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ inputs.cacheKey }}
      - id: checkout-files
        name: Checkout files
        run: |
          REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          BRANCH="${GITHUB_REF/#refs\/heads\//}"

          # Reference https://github.com/actions/checkout/issues/172
          # Following code is based on logs of actions/checkout@v, with sparseCheckout stuff inserted in the middle
          echo "Syncing repository: $GITHUB_REPOSITORY"
          echo "Working directory is '$(pwd)' GITHUB_WORKSPACE=$GITHUB_WORKSPACE BRANCH=$BRANCH"
          git version
          git init $GITHUB_WORKSPACE
          git remote add origin https://github.com/$GITHUB_REPOSITORY
          git config --local gc.auto 0
          # Now interesting part
          git sparse-checkout init --cone
          # Add here contents of sparse-checkout line by line
          git sparse-checkout set packages/eds-core-react packages/eds-tokens packages/eds-icons packages/eds-lab-react packages/eds-utils
          # echo ...
          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=10 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
      - id: cache-pnpm-store
        name: Cache pnpm-store
        uses: actions/cache@v3
        with:
          path: |
            node_modules/.bin/pnpm
            node_modules/pnpm
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-and-store-${{ hashFiles('packages/**/pnpm-lock.yaml') }}
      - name: Install pnpm
        # if: steps.cache-pnpm-store.outputs.cache-hit != 'true'
        run: npm i --no-save pnpm
      - name: Install dependencies recursively
        # if: steps.cache-pnpm-store.outputs.cache-hit != 'true'
        run: node_modules/.bin/pnpm m i
